---
dag:
  repository: moj-analytical-services/analytical-platform-airflow-python-example
  tag: 2.0.0
  env_vars:
    FOO: "bar"
  tasks:
    task_one:
      env_vars:
        TASK: "FIRST"
    task_two:
      env_vars:
        TASK: "SECOND"
      dependencies: [task_one]
    task_three:
      env_vars:
        TASK: "THIRD"
      dependencies: [task_two]
    task_four:
      env_vars:
        TASK: "FOURTH"
        mode: "failure"
      dependencies: [task_three]
    task_five:
      env_vars:
        AWS_DEFAULT_REGION: "eu-west-2"
        TASK: "FIFTH"
        N_TASK: 5
      dependencies: [task_four]
    task_six:
      env_vars:
        TASK: "SIXTH"

notifications:
  slack_channel: analytical-platform-airflow-testing

maintainers:
  - jacobwoffenden

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
