---
dag:
  repository: moj-analytical-services/analytical-platform-airflow-python-example
  tag: 2.0.0
  env_vars:
    FOO: "bar"
  tasks:
    task_one:
      env_vars:
        TASK: "1"
    task_two:
      env_vars:
        TASK: "2"
      dependencies: [task_one]
    task_three:
      env_vars:
        TASK: "3"
        MODE: "benchmark"
        FOO: "baz"
      compute_profile: gpu-spot-8vcpu-32gb
      dependencies: [task_two]

maintainers:
  - jacobwoffenden

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
