---
dag:
  repository: moj-analytical-services/analytical-platform-airflow-python-example
  tag: 2.0.0
  tasks:
    init:
      env_vars:
        MODE: "basic"
    phase-one:
      env_vars:
        MODE: "basic"
      dependencies: [init]
    phase-two:
      env_vars:
        MODE: "basic"
      dependencies: [phase-one]
    phase-three:
      env_vars:
        MODE: "benchmark"
      compute_profile: gpu-spot-8vcpu-32gb
      dependencies: [phase-one, phase-two]

maintainers:
  - jacobwoffenden
  - julialawrence

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
