---
dag:
  repository: moj-analytical-services/airflow-load-em-data
  tag: v0.2.109
  compute_profile: general-spot-1vcpu-4gb
  catchup: false
  depends_on_past: false
  max_active_runs: 1
  env_vars:
    SUPPLIER_NAME: "buddi"
    SYSTEM_NAME: "buddi"
    DATASET_NAME: "buddi"
    DELIVERY_DATE: "2025-10-16"
    AWS_METADATA_SERVICE_TIMEOUT: 60
    AWS_METADATA_SERVICE_NUM_ATTEMPTS: 5
    AWS_DEFAULT_REGION: "eu-west-2"
    AWS_ATHENA_QUERY_EXTRACT_REGION: "eu-west-2"
    AWS_DEFAULT_EXTRACT_REGION: "eu-west-2"

  tasks:
    load_buddi_device_fittings:
      env_vars:
        TABLE_NAME: "device_fittings"

    load_buddi_devices:
      env_vars:
        TABLE_NAME: "devices"

    load_buddi_enrollments:
      env_vars:
        TABLE_NAME: "enrollments"

    load_buddi_locations:
      env_vars:
        TABLE_NAME: "locations"

    load_buddi_verifications:
      env_vars:
        TABLE_NAME: "verifications"

    load_buddi_wearers:
      env_vars:
        TABLE_NAME: "wearers"

notifications:
  emails:
    - Matt.Heery@justice.gov.uk
    - Luke.Williams6@justice.gov.uk
  slack_channel: em-engineers-moj-madetech

iam:
  external_role: arn:aws:iam::976799291502:role/airflow-prod-load-buddi

maintainers:
  - matt-heery
  - kraihanmoj
  - luke-a-williams

tags:
  business_unit: HMPPS
  owner: matt.heery@justice.gov.uk # for now....
