dag:
  repository: ministryofjustice/coat-cur-data-pipeline
  tag: v1.0.1-dev
  max_active_runs: 1
  retries: 2
  retry_delay: 120
  schedule: "0 6 * * *"

maintainers:
  - tamsinforbes
  - connormaglynn
  - abachleda-baca
  - stefanskyhristov
  - ratna-kurapati-moj

iam:
  athena: write
  glue: true
  s3_read_only:
    - mojap-data-production-coat-cur-reports-v2-hourly/*
  kms:
    - arn:aws:kms:eu-west-1:593291632749:key/0409ddbc-b6a2-46c4-a613-6145f6a16215
tags:
  business_unit: Platforms
  owner: anthony.bishop@justice.gov.uk

notifications:
  slack_channel: cloud-optimisation-and-accountability-team
