---
dag:
  repository: moj-analytical-services/airflow-geography
  tag: v1.5.1
  python_dag: true

iam:
  athena: write
  glue: true
  s3_read_write:
    - alpha-geography/dev/addressbase/*

secrets:
  - osdatahub-api-key

maintainers:
  - p-sin
  - gwionap

tags:
  business_unit: OPG
  owner: philip.sinfield@justice.gov.uk
