dag:
  repository: moj-analytical-services/probation-performance-extraction
  tag: v0.0.13
  schedule: "30 6 * * *"

iam:
  athena: write

  s3_write_only:
    - alpha-probation-performance-extracts/*

  s3_read_only:
    - mojap-derived-tables/prod/models/domain_name=probation/database_name=delius/*
    - mojap-derived-tables/prod/models/domain_name=probation/database_name=derived_delius_dim/*
    - mojap-derived-tables/prod/models/domain_name=probation/database_name=derived_delius_stg/*
    - mojap-derived-tables/prod/models/domain_name=probation/database_name=derived_delius/*
    - mojap-derived-tables/prod/models/domain_name=general/database_name=common_lookup/*

maintainers:
  - hcgk
  - yvette-justice

notifications:
  emails:
    - henry.goldsack@justice.gov.uk

tags:
  business_unit: HQ
  owner: communityperformanceenquiries@justice.gov.uk
