dag:
  repository: moj-analytical-services/airflow-dmet-property
  tag: v0.4.4
  compute_profile: "general-on-demand-1vcpu-4gb"

maintainers:
  - jnayak-moj

secrets:
  - api-key

iam:
  s3_read_write:
    - mojap-land-dev/property/cde/*

tags:
  business_unit: Central Digital
  owner: jyotiranjan.nayak@justice.gov.uk
