---
dag:
  repository: moj-analytical-services/airflow-load-em-data
  tag: v0.2.98-preprod
  compute_profile: general-spot-1vcpu-4gb
  catchup: true
  depends_on_past: false
  schedule: "0 3 * * *"
  start_date: "2025-09-02"
  max_active_runs: 1
  env_vars:
    SUPPLIER_NAME: "serco"
    SYSTEM_NAME: "fms"
    DELIVERY_DATE: "{{ ds }}"
    AWS_DEFAULT_REGION: "eu-west-2"
    AWS_ATHENA_QUERY_EXTRACT_REGION: "eu-west-2"
    AWS_DEFAULT_EXTRACT_REGION: "eu-west-2"
    DATA_INTERVAL_START: "{{ data_interval_start }}"
    DATA_INTERVAL_END: "{{ data_interval_end }}"

notifications:
  emails:
    - EMDataEngineering@justice.gov.uk
  slack_channel: electronic-monitoring-data-hub-preprod-notifications

iam:
  external_role: arn:aws:iam::443370694497:role/airflow-prod-load-fms-pp

maintainers:
  - matt-heery

tags:
  business_unit: HMPPS
  owner: EMDataEngineering@justice.gov.uk
