dag:
  repository: ministryofjustice/nca-offloc-dag
  tag: v1.0.16
  catchup: false
  depends_on_past: false
  is_paused_upon_creation: false
  max_active_runs: 1
  retries: 1
  retry_delay: 150
  schedule: None # "58 9 * * Tue"
  start_date: "2025-03-18"
  tasks:
    task:
      compute_profile: "general-on-demand-1vcpu-4gb"

iam:
  athena: write
  glue: true
  kms:
    - arn:aws:kms:eu-west-2:505940320338:key/a4e16805-b10a-4996-9e90-fefe8674ecc7
  s3_read_write:
    - mojap-hub-exports/*

secrets:
  - user
  - pass

maintainers:
  - vonbraunbates
  - gwionap

tags:
  business_unit: Central Digital
  owner: francesca.von.braun-bates@justice.gov.uk

notifications:
  emails:
    - francesca.von.braun-bates@justice.gov.uk
  slack_channel: ct-data-engineering
