---
tags:
  business_unit: HQ
  owner: analytical-platform@justice.gov.uk

dag:
  repository: moj-analytical-services/analytical-platform-airflow-python-example
  tag: 1.0.2
  compute_profile: gpu-spot-8vcpu-32gb

iam:
  external_role: arn:aws:iam::123456789012:role/this-is-not-a-real-role

maintainers:
  - jacobwoffenden
  - julialawrence
