---
dag:
  repository: moj-analytical-services/airflow-report-extractor
  tag: v1.08
  schedule: "0 7-18 * * 1-5"
  retries: 1
  retry_delay: 60
  env_vars:
    REPORT_APP: "splashbi"
    REPORT_RUNTIME_ENV: "prod"
    REPORT_RUN_MODE: "extract"
  tasks:
    # === Commercial Synergy GRNI ===
    po_sscl_details:
      env_vars:
        REPORT_NAME: "po_sscl_details"

    # === Commercial Synergy headers ===

    cts-supplier_headers:
      env_vars:
        REPORT_NAME: "cts-supplier_headers"
    laa-supplier_headers:
      env_vars:
        REPORT_NAME: "laa-supplier_headers"
    opg-supplier_headers:
      env_vars:
        REPORT_NAME: "opg-supplier_headers"
    yjb-supplier_headers:
      env_vars:
        REPORT_NAME: "yjb-supplier_headers"
    ima-supplier_headers:
      env_vars:
        REPORT_NAME: "ima-supplier_headers"
    moj-supplier_headers:
      env_vars:
        REPORT_NAME: "moj-supplier_headers"
    pbd-supplier_headers:
      env_vars:
        REPORT_NAME: "pbd-supplier_headers"
    jac-supplier_headers:
      env_vars:
        REPORT_NAME: "jac-supplier_headers"
    nms-supplier_headers:
      env_vars:
        REPORT_NAME: "nms-supplier_headers"
    wls-supplier_headers:
      env_vars:
        REPORT_NAME: "wls-supplier_headers"

    # === Commercial Synergy suppliers ===

    cts-supplier_sites:
      env_vars:
        REPORT_NAME: "cts-supplier_sites"
    jac-supplier_sites:
      env_vars:
        REPORT_NAME: "jac-supplier_sites"
    moj-supplier_sites:
      env_vars:
        REPORT_NAME: "moj-supplier_sites"
    opg-supplier_sites:
      env_vars:
        REPORT_NAME: "opg-supplier_sites"
    wls-supplier_sites:
      env_vars:
        REPORT_NAME: "wls-supplier_sites"
    ima-supplier_sites:
      env_vars:
        REPORT_NAME: "ima-supplier_sites"
    laa-supplier_sites:
      env_vars:
        REPORT_NAME: "laa-supplier_sites"
    nms-supplier_sites:
      env_vars:
        REPORT_NAME: "nms-supplier_sites"
    pbd-supplier_sites:
      env_vars:
        REPORT_NAME: "pbd-supplier_sites"
    yjb-supplier_sites:
      env_vars:
        REPORT_NAME: "yjb-supplier_sites"

    # === HR iExpenses Reports ===
    moj-iexp01:
      env_vars:
        REPORT_NAME: "moj-iexp01"
    laa-iexp01:
      env_vars:
        REPORT_NAME: "laa-iexp01"
    opg-iexp01:
      env_vars:
        REPORT_NAME: "opg-iexp01"
    cts-iexp01:
      env_vars:
        REPORT_NAME: "cts-iexp01"
    nms-iexp01:
      env_vars:
        REPORT_NAME: "nms-iexp01"

    # === HR Non Sickness Absence Reports ===
    cts-hr-a-01-nonsick:
      env_vars:
        REPORT_NAME: "cts-hr-a-01"
    laa-hr-a-01-nonsick:
      env_vars:
        REPORT_NAME: "laa-hr-a-01"
    nms-hr-a-01-nonsick:
      env_vars:
        REPORT_NAME: "nms-hr-a-01"
    opg-hr-a-01-nonsick:
      env_vars:
        REPORT_NAME: "opg-hr-a-01"
    moj-hr-a-01-nonsick:
      env_vars:
        REPORT_NAME: "moj-hr-a-01"
    moj-hr-a-04-nonsick:
      env_vars:
        REPORT_NAME: "moj-hr-a-04-nonsick"

    # === HR Sick Absence Reports ===
    moj-hr-a-04-sick:
      env_vars:
        REPORT_NAME: "moj-hr-a-04-sick"
    moj-hr-wf-60-sickleave:
      env_vars:
        REPORT_NAME: "moj-hr-wf-60"

    # === HR Remuneration Reports ===
    cts-hr-rew-02-remuneration:
      env_vars:
        REPORT_NAME: "cts-hr-rew-02"
    laa-hr-rew-02-remuneration:
      env_vars:
        REPORT_NAME: "laa-hr-rew-02"
    nms-hr-rew-02-remuneration:
      env_vars:
        REPORT_NAME: "nms-hr-rew-02"
    opg-hr-rew-02-remuneration:
      env_vars:
        REPORT_NAME: "opg-hr-rew-02"
    moj-hr-rew-02-remuneration:
      env_vars:
        REPORT_NAME: "moj-hr-rew-02"

    # === HR Staffing Reports ===
    moj-hr-wf-59-leavers:
      env_vars:
        REPORT_NAME: "moj-hr-wf-59"
    moj-hr-wf-62-sip:
      env_vars:
        REPORT_NAME: "moj-hr-wf-62"
    moj-hr-wf-64-starters:
      env_vars:
        REPORT_NAME: "moj-hr-wf-64"

iam:
  s3_read_write:
    - mojap-land/corporate/report_extractor_prod/splashbi/*

secrets:
  - splashbi-credentials

notifications:
  slack_channel: dmet-corp-notifications
  emails:
    - william.orr@justice.gov.uk
    - Supratik.Chowdhury@justice.gov.uk
    - mohammed.ahad1@justice.gov.uk
    - laurence.droy@justice.gov.uk

maintainers:
  - williamorrie
  - moj-supratikc
  - morezwan
  - ltd-pa

tags:
  business_unit: Central Digital
  owner: supratik.chowdhury@justice.gov.uk
