---
dag:
  repository: moj-analytical-services/airflow-report-extractor
  tag: v1.4.0
  schedule: "0 7-18 * * 1-5"
  env_vars:
    REPORT_APP: "splashbi"
    REPORT_RUNTIME_ENV: "prod"
    REPORT_RUN_MODE: "extract"
    DISABLE_SCHEDULING: True
  tasks:
    # === HR iExpenses Reports ===
    moj-iexp01:
      env_vars:
        REPORT_NAME: "moj-iexp01"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"
    laa-iexp01:
      env_vars:
        REPORT_NAME: "laa-iexp01"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"
    opg-iexp01:
      env_vars:
        REPORT_NAME: "opg-iexp01"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"
    cts-iexp01:
      env_vars:
        REPORT_NAME: "cts-iexp01"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"
    nms-iexp01:
      env_vars:
        REPORT_NAME: "nms-iexp01"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"

    # === HR Non Sickness Absence Reports ===
    cts-hr-a-01-nonsick:
      env_vars:
        REPORT_NAME: "cts-hr-a-01"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"
    laa-hr-a-01-nonsick:
      env_vars:
        REPORT_NAME: "laa-hr-a-01"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"
    nms-hr-a-01-nonsick:
      env_vars:
        REPORT_NAME: "nms-hr-a-01"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"
    opg-hr-a-01-nonsick:
      env_vars:
        REPORT_NAME: "opg-hr-a-01"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"
    moj-hr-a-01-nonsick:
      env_vars:
        REPORT_NAME: "moj-hr-a-01"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"
    moj-hr-a-04-nonsick:
      env_vars:
        REPORT_NAME: "moj-hr-a-04-nonsick"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"

    # === HR Sick Absence Reports ===
    moj-hr-a-04-sick:
      env_vars:
        REPORT_NAME: "moj-hr-a-04-sick"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"
    moj-hr-wf-60-sickleave:
      env_vars:
        REPORT_NAME: "moj-hr-wf-60"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"

    # === HR Remuneration Reports ===
    cts-hr-rew-02-remuneration:
      env_vars:
        REPORT_NAME: "cts-hr-rew-02"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"
    laa-hr-rew-02-remuneration:
      env_vars:
        REPORT_NAME: "laa-hr-rew-02"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"
    nms-hr-rew-02-remuneration:
      env_vars:
        REPORT_NAME: "nms-hr-rew-02"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"
    opg-hr-rew-02-remuneration:
      env_vars:
        REPORT_NAME: "opg-hr-rew-02"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"
    moj-hr-rew-02-remuneration:
      env_vars:
        REPORT_NAME: "moj-hr-rew-02"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"

    # === HR Staffing Reports ===
    moj-hr-wf-59-leavers:
      env_vars:
        REPORT_NAME: "moj-hr-wf-59"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"
    moj-hr-wf-62-sip:
      env_vars:
        REPORT_NAME: "moj-hr-wf-62"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"
    moj-hr-wf-64-starters:
      env_vars:
        REPORT_NAME: "moj-hr-wf-64"
        REPORT_SECRET_ID: "sbi-user-mojsupratikc"

    # === Finance GL Reports ===
    cts-gl22:
      env_vars:
        REPORT_NAME: "cts_gl22"
        REPORT_SECRET_ID: "sbi-user-csheldon"
    laa-gl22:
      env_vars:
        REPORT_NAME: "laa_gl22"
        REPORT_SECRET_ID: "sbi-user-csheldon"
    moj-gl22:
      env_vars:
        REPORT_NAME: "moj_gl22"
        REPORT_SECRET_ID: "sbi-user-csheldon"
    noms-gl22:
      env_vars:
        REPORT_NAME: "noms_gl22"
        REPORT_SECRET_ID: "sbi-user-csheldon"
    opg-gl22:
      env_vars:
        REPORT_NAME: "opg_gl22"
        REPORT_SECRET_ID: "sbi-user-csheldon"

iam:
  s3_read_write:
    - mojap-land/corporate/report_extractor_prod/splashbi/*

secrets:
  - sbi-user-csheldon
  - sbi-user-mojsupratikc
  - sbi-user-ltdpa
  - sbi-user-morezwan
  - sbi-user-williamorrie
  - sbi-user-spare

notifications:
  slack_channel: dmet-corp-notifications
  emails:
    - william.orr@justice.gov.uk
    - Supratik.Chowdhury@justice.gov.uk
    - mohammed.ahad1@justice.gov.uk
    - laurence.droy@justice.gov.uk

maintainers:
  - williamorrie
  - moj-supratikc
  - morezwan
  - ltd-pa
  - Csheldon155

tags:
  business_unit: Central Digital
  owner: supratik.chowdhury@justice.gov.uk
