---
dag:
  repository: ministryofjustice/analytical-platform-airflow-cadet-deployer
  tag: 1.2.4
  compute_profile: general-on-demand-16vcpu-64gb
  catchup: false
  hmcts_sdp_networking: true
  env_vars:
    DEPLOY_ENV: dev
    DBT_PROFILE_WORKGROUP: dbt-xhibit
    DBT_PROJECT: sdp_tables
    WORKFLOW_NAME: deploy-one-crown-sdp-dev
    DBT_SELECT_CRITERIA: "+path:models/customers +path:models/orders"
    BRANCH: feature/sdp-dev-pool-airflow
    MODE: build

maintainers:
  - jovita-brundziene
  - Andy-Cook

secrets:
  - sdp-id-dev
  - sdp-sec-dev
  - sdp-ten-id

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/dev/*

tags:
  business_unit: Central Digital
  owner: jovita.brundzienem@justice.gov.uk
