---
dag:
  repository: ministryofjustice/analytical-platform-airflow-cadet-deployer
  tag: 1.4.1
  compute_profile: general-on-demand-16vcpu-64gb
  catchup: false
  env_vars:
    DEPLOY_ENV: prod
    DBT_PROFILE_WORKGROUP: dbt-xhibit
    DBT_PROJECT: mojap_derived_tables
    WORKFLOW_NAME: deploy-ccd-divorce-curated
    DBT_SELECT_CRITERIA: tag:ccd_divorce
    BRANCH: main
    MODE: build
    THREAD_COUNT: 10

maintainers:
  - DanJ-MOJ
  - Andy-Cook
  - AntonyJScott

secrets:
  - github-key

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/prod/*

tags:
  business_unit: Central Digital
  owner: cft_data_engineering@justice.gov
