dag:
  repository: moj-analytical-services/airflow-sdt
  tag: v4.4.0
  compute_profile: "general-spot-2vcpu-8gb"
  env_vars:
    AIRFLOW_ENVIRONMENT: "PRODUCTION"
  outlets:
    - "s3://alpha-app-safety-diagnostic-tool/"
  inlets:
    - "s3://alpha-viper/scores_2/"
    - "s3://alpha-safety-mi/prisons_ds/assaults_proc_locations/assaults_proc_locations.csv"
    - "s3://alpha-app-safety-diagnostic-tool/txt_sh_pop.feather"
    - "s3://alpha-app-safety-diagnostic-tool/vio-summary/VIO_SUMMARY.csv"
  schedule:
    datasets:
      - "s3://alpha-viper/scores_2/"
      - "s3://alpha-safety-mi/prisons_ds/assaults_proc_locations/assaults_proc_locations.csv"
      - "s3://alpha-app-safety-diagnostic-tool/txt_sh_pop.feather"
      - "s3://alpha-app-safety-diagnostic-tool/vio-summary/VIO_SUMMARY.csv"

iam:
  athena: write

  s3_read_only:
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_dbt/*
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_sensitive/*
    - alpha-safety-mi/prisons_ds/*
    - alpha-viper/*
    - alpha-test-iam-builer/db/*
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_dn/*
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=prison_derived/*
    - mojap-derived-tables/seeds/nomis_dn/*
    - mojap-derived-tables/seeds/nomis_dn/*
    - alpha-nomis/nomis_dn/*

  s3_read_write:
    - alpha-anvil-lookups/*
    - alpha-app-safety-diagnostic-tool/*

notifications:
  emails:
    - sdt-support@justice.gov.uk

maintainers:
  - miller-william
  - lauratraceymoj

tags:
  business_unit: HMPPS
  owner: william.miller1@justice.gov.uk
