dag:
  repository: moj-analytical-services/asc-test-airflow
  tag: v1.0.1.dev3

maintainers:
  - antonyjscott

notifications:
  slack_channel: de-probation-airflow-dev

tags:
  business_unit: HQ
  owner: antony.scott@justice.gov.uk
