---
dag:
  repository: ministryofjustice/analytical-platform-airflow-cadet-deployer
  tag: 1.1.26
  compute_profile: general-on-demand-8vcpu-32gb
  schedule: "0 13 * * 1"
  catchup: false
  outlets:
    - "s3://mojap-derived-tables/prod/laa-weekly/"
  env_vars:
    DEPLOY_ENV: sandpit
    DBT_PROFILE_WORKGROUP: dbt-weekly
    DBT_PROJECT: mojap_derived_tables
    WORKFLOW_NAME: laa-weekly
    DBT_SELECT_CRITERIA: tag:laa_crime
    BRANCH: main
    MODE: build

maintainers:
  - jhpyke

secrets:
  - github-key

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/prod/*

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
