---
dag:
  repository: ministryofjustice/analytical-platform-airflow-cadet-deployer
  tag: 1.1.17
  compute_profile: general-on-demand-16vcpu-64gb
  schedule: "0 9-11 * * *"
  catchup: false
  outlets:
    - "s3://mojap-derived-tables/prod/cica-daily/"
  env_vars:
    DEPLOY_ENV: sandpit
    DBT_PROFILE_WORKGROUP: dbt-cica
    DBT_PROJECT: mojap_derived_tables
    WORKFLOW_NAME: cica-daily
    DBT_SELECT_CRITERIA: tag:cica_daily
    BRANCH: main
    MODE: build

maintainers:
  - jhpyke

secrets:
  - github-key

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/prod/*

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
