dag:
  repository: ministryofjustice/airflow-cadet-post-hook-copy
  tag: v1.1.0
  catchup: false
  env_vars:
    SOURCE_PATH: "post-hook/prod/domain_name=public_protection/database_name=public_protection_int/table_name=int_audit_log_hearing/extraction_timestamp=2026-07-09T11:21:41.957/20260709_112200_00133_mkrdy_ab2a798f-0ed9-449f-a14a-250057ca953a.gz"
    SOURCE_BUCKET: "probation-datalake-prod-20260112145345979100000002"
    TARGET_BUCKET: "moj-reg-prod"
    PROJECT_NAME: "cadet-pb-hearing-audit-prod"
    DATABASE_NAME: "pb_hearing"
    TABLE_NAME: "hearing_audit_log"
    AWS_REGION: "eu-west-2"
    FILE_EXTENSION: "json"

maintainers:
  - lalithanagarur
  - joephillipsjustice

notifications:
  emails:
    - lalitha.nagarur3@justice.gov.uk
    - joseph.phillips@justice.gov.uk
    - ProbationDataEngineering@justice.gov.uk
  slack_channel: de-probation-airflow-prod

iam:
  external_role: arn:aws:iam::189157455002:role/probation-cadet-prod

tags:
  business_unit: HMPPS
  owner: ProbationDataEngineering@justice.gov.uk
