dag:
  repository: moj-analytical-services/airflow-prison-network-app
  tag: 1.6.13
  catchup: false
  depends_on_past: false
  is_paused_upon_creation: false
  max_active_runs: 1
  retries: 3
  retry_delay: 100
  schedule: None
  start_date: "2025-04-21"
  tasks:
    task:
      compute_profile: "general-on-demand-16vcpu-64gb"

iam:
  athena: write

  s3_read_only:
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_dbt/*
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_sensitive/*
    - alpha-app-bentham-app/*
    - alpha-app-hmpps-ct-tool/*
    - mojap-land/hmpps/prisoner-money/*
    - alpha-app-prison-visitor-app/*
    - hmpps-pathfinder-prod-curated/*
    - moj-reg-prod-curated/hmpps-pathfinder-prod/data/*
    - alpha-mojap-curated-xhibit/v2/xhibit_der/*
    - moj-reg-prod-curated/data-eng-uploader-prod/data/database_name=prison_video_calls/*
    - alpha-data-linking/v5/products/internal/*
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_dn/*
    - mojap-derived-tables/seeds/nomis_dn/*
    - mojap-derived-tables/prod/models/domain_name=courts/*

  s3_read_write:
    - alpha-prison-network-app/*
    - alpha-app-prison-network-app/*
    - alpha-prisoner-money/*
    - alpha-athena-dump/*
    - alpha-athena-query-dump/*

notifications:
  emails:
    - matthew.funnell@justice.gov.uk
    - dean.lundie@justice.gov.uk
  slack_channel: intel-app-maintenance

maintainers:
  - mattfunnell
  - d-lundie

tags:
  business_unit: HMPPS
  owner: matthew.funnell@justice.gov.uk
