dag:
  repository: moj-analytical-services/prisons-data-discovery
  tag: v1.0.1
  compute_profile: "general-spot-2vcpu-8gb"

iam:
  athena: write

  s3_read_only:
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_sensitive/table_name=persons_wap/*

  s3_read_write:
    - alpha-safety-mi/*

maintainers:
  - lauratraceymoj

tags:
  business_unit: HMPPS
  owner: laura.tracey@justice.gov.uk
