---
dag:
  repository: moj-analytical-services/airflow-load-em-data
  tag: v0.3.10-dev
  compute_profile: general-spot-1vcpu-4gb
  catchup: false
  depends_on_past: false
  schedule: "0 * * * *"
  start_date: "2025-04-15"
  max_active_runs: 1
  env_vars:
    SUPPLIER_NAME: "capita"
    SYSTEM_NAME: "blob_storage"
    AWS_DEFAULT_REGION: "eu-west-2"
    AWS_ATHENA_QUERY_EXTRACT_REGION: "eu-west-2"
    AWS_DEFAULT_EXTRACT_REGION: "eu-west-2"

notifications:
  emails:
    - EMDataEngineering@justice.gov.uk
  slack_channel: electronic-monitoring-data-hub-test-notifications

iam:
  external_role: arn:aws:iam::800964199911:role/airflow-dev-load-capita-blob-storage

maintainers:
  - matt-heery
  - kraihanmoj
  - jono-basford-moj

tags:
  business_unit: HMPPS
  owner: EMDataEngineering@justice.gov.uk
