---
dag:
  repository: moj-analytical-services/CourtCaseLoad
  tag: 2.0.0

notifications:
  emails:
    - flo.ogunpola@justice.gov.uk

maintainers:
  - fogunpola

tags:
  business_unit: "HMCTS"
  owner: "analytical-platform@justice.gov.uk"
