---
dag:
  repository: moj-analytical-services/airflow-laa-data-extractor
  tag: v0.4.1.dev1
  retries: 2
  retry_delay: 300
  env_vars:
    BUCKET: "alpha-mojap-laa"
    SERVICE: "athena"
    ORACLE_USER: "LAASTATS_ARC"
    DATABASE_NAME: "laa_datashare"
    TABLE_PREFIX: "DSA_SOL_"
    MOJAP_DB_VER: "v1"

iam:
  athena: write
  glue: true
  s3_read_write:
    - alpha-mojap-laa/*

secrets:
  - username
  - password
  - db-dsn

notifications:
  emails:
    - Damilola.Oyebade@justice.gov.uk
  slack_channel: laa-de-alerts

maintainers:
  - dami-moj

tags:
  business_unit: LAA
  owner: Damilola.Oyebade@justice.gov.uk
