---
dag:
  repository: moj-analytical-services/analytical-platform-airflow-python-example
  tag: 2.13.0
  retries: 3
  retry_delay: 150
  schedule: "*/5 * * * *"

notifications:
  slack_channel: analytical-platform-airflow-testing

maintainers:
  - jacobwoffenden

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
