dag:
  repository: airflow-cf-misconduct
  tag: v0.0.76
  # not sure if two rows below are needed?
  dag_id: cf_misconduct.cf_misconduct_ml
  default_args: default_args
  #catchup: false
  depends_on_past: false
  email_on_failure: True
  #is_paused_upon_creation: false
  #max_active_runs: 1
  #retries: 3
  #retry_delay: 100
  schedule: None
  start_date: "2022-01-01"

  tasks:
    model_tuning:
      env_vars:
        CONTAINER_NAME: "model_tuning"
        PYTHON_SCRIPT_NAME: "tuning.py",
        AWS_METADATA_SERVICE_TIMEOUT: "60"
        AWS_METADATA_SERVICE_NUM_ATTEMPTS": "5"
        AWS_DEFAULT_REGION": "eu-west-1"

    create_predictions:
      env_vars:
        CONTAINER_NAME: "create_predictions"
        PYTHON_SCRIPT_NAME: "create_pred.py"
        AWS_METADATA_SERVICE_TIMEOUT: "60"
        AWS_METADATA_SERVICE_NUM_ATTEMPTS: "5"
        AWS_DEFAULT_REGION: "eu-west-1"

tasks["model_tuning"] >> tasks["create_predictions"]

iam:
  # athena: write
  # glue: true
  # s3_read_write:
  #   - alpha-mojap-ccde/dev/pcol_raw_data/*

secrets:
  # - pds

# notifications:
#   emails:
#     - Jhenielle.Francis@justice.gov.uk

maintainers:
  - jhenfrancis
  - sheilz81
  - tomd-moj

tags:
  business_unit: HQ
  owner: Jhenielle.Francis@justice.gov.uk
