INIT_IMAGE_VERSION = "v0.0.9"
INIT_RE_PATTERN = "^v0.0.[1-6]$"
DOWNSTREAM_DAGS = {
    "bentham_app_2": {
        "dag_id": "bentham_app_airflow",
        "dag_folder": "bentham",
        "dag_tools_version": "v0.0.9",
        "dependencies": [
            "nomis-current_pop",
            "nomis-offender_location",
            "nomis-offenders",
            "nomis-offender_bookings",
        ],
    },
    "drugs_app": {
        "dag_id": "drugs_app_airflow",
        "dag_folder": "drugs_app",
        "dag_tools_version": "v0.0.9",
        "dependencies": [
            "nomis-finds",
            "nomis-finds_detail",
            "nomis-offenders",
            "nomis-offender_bookings",
            "nomis-incident_case_parties",
        ],
    },
    "prison_network_app": {
        "dag_id": "prison-network-app",
        "dag_folder": "prison-network",
        "dag_tools_version": "v0.0.9",
        "dependencies": [
            "nomis-assaults",
            "nomis-current_pop",
            "nomis-disorder",
            "nomis-finds",
            "nomis-involvements",
            "nomis-offender_location",
            "nomis-offender_alerts",
            "nomis-offender_bookings",
            "nomis-offender_visits",
            "nomis-offenders",
            "nomis-agency_internal_locations",
            "nomis-bed_assignment_histories",
            "nomis-offender_charges",
            "nomis-offender_profile_details",
            "nomis-profile_codes",
        ],
    },
    "sdt": {
        "dag_id": "sdt",
        "dag_folder": "sdt",
        "dag_tools_version": "v0.0.9",
        "dependencies": [
            "nomis-incident_cases",
            "nomis-offender_alerts",
            "nomis-offender_iep_levels",
            "nomis-offender_bookings",
            "nomis-offenders",
            "nomis-current_pop",
            "nomis-assaults",
            "nomis-selfharm",
            "nomis-selfharm_detail",
            "nomis-disorder",
            "nomis-finds",
            "nomis-finds_detail",
            "nomis-offender_location",
            "nomis-involvements",
            "nomis-questionnaire_questions",
            "nomis-questionnaire_answers",
            "nomis-incident_case_questions",
            "nomis-incident_case_responses",
            "nomis-bed_assignment_histories",
            "nomis-agency_internal_locations",
            "nomis-reference_codes",
            "nomis-offender_visits",
            "nomis-offender_sentence_terms",
            # "nomis-ao-tables",
        ],
        "priority_weight": 3,
    },
}

NOMIS_TABLES = [
    "offenders",
    "offender_identifiers",
    "incident_cases",
    "incident_case_responses",
    "addresses",
    "persons",
    "staff_members",
    "phones",
    "internet_addresses",
    "staff_user_accounts",
    "offender_physical_attributes",
    "offender_health_problems",
    "offender_profile_details",
    "random_testing_programs",
    "offender_visits",
    "offender_visit_visitors",
    "address_usages",
    "offender_contact_persons",
    "offender_cases",
    "court_events",
    "court_event_charges",
    "rehabilitation_providers",
    "offender_rehab_providers",
    "gang_non_associations",
    "gangs",
    "offender_gang_affiliations",
    "offender_gang_evidences",
    "offender_gang_invests",
    "offender_na_details",
    "offender_non_associations",
    "offender_person_restricts",
    "offender_sentence_terms",
    "offender_sent_calculations",
    "offender_sentence_charges",
    "offender_charges",
    "offender_imprison_statuses",
    "offender_release_details",
    "offender_sentences",
    "offender_alerts",
    "offender_iep_levels",
    "offender_oic_sanctions",
    "offender_rehab_decisions",
    "offender_bookings",
    "offender_risk_predictors",
    "offender_assessment_items",
    "offender_assessments",
    "offender_sentence_statuses",
    "offender_sentence_adjusts",
    "offender_reorder_sentences",
    "reference_codes",
    "agency_locations",
    "profile_codes",
    "program_services",
    "questionnaire_questions",
    "questionnaire_answers",
    "questionnaires",
    "imprisonment_statuses",
    "incident_statuses",
    "offences",
    "questionnaire_roles",
    "orders",
    "assessments",
    "statutes",
    "movement_reasons",
    "offence_indicators",
    "offence_result_codes",
    "areas",
    "sentence_calc_types",
    "incident_case_parties",
    "incident_case_questions",
    "agency_internal_locations",
    "offender_external_movements",
    "bed_assignment_histories",
    "offender_csip_attendees",
    "offender_csip_factors",
    "offender_csip_intvw",
    "offender_csip_plans",
    "offender_csip_reports",
    "offender_csip_reviews",
    "profile_types",
    "offender_transactions",
    "agency_visit_times",
    "offender_visit_orders",
    "offender_restrictions",
    "agency_visit_slots",
    "corporates",
    "user_accessible_caseloads",
    "caseload_agency_locations",
    "offender_ind_schedules",
    "offender_vo_visitors",
    "offender_course_attendances",
    "offender_case_notes",
    "oic_hearing_notices",
    "oic_hearing_results",
    "oic_hearings",
    "oic_offences",
    "oic_sanction_limits",
    "offender_program_profiles",
    "agency_incident_parties",
    "agency_incident_charges",
    "agency_incident_repairs",
    "agency_incidents",
    "agy_inc_investigations",
    "agy_int_loc_amendments",
    "offender_ppty_con_txns",
    "course_activities",
    "offender_key_date_adjusts",
    "sentence_adjustments",
    "sentence_term_adjustments",
    "offender_adjustment_txns",
    "offender_curfews",
    "hdc_status_trackings",
    "order_types",
    "order_purposes",
    "reference_domains",
    "transaction_types",
    "offender_substance_treatments",
    "offender_substance_uses",
    "offender_substance_details",
    "curfew_addresses",
    "hdc_request_referrals",
    "hdc_board_decisions",
    "offender_medical_treatments",
    "offender_sent_conditions",
    "offender_licence_recalls",
    "merge_transactions",
    "merge_transaction_logs",
    "offender_educations",
    "hdc_calc_exclusion_reasons"
    # "tag_images",
]

NOMIS_TABLE_RESOURCES = {
    "offender_transactions": 40,
    "offender_course_attendances": 48,
    "offender_case_notes": 16,
    "offender_visit_visitors": 8,
    "offender_profile_details": 4,
    "offender_external_movements": 8,
    "bed_assignment_histories": 8,
    "offender_ind_schedules": 4,
}

NOMIS_TABLE_TIMEOUTS = {
    "offender_transactions": 300,
    "offender_course_attendances": 300,
}

AO_DEPENDENCIES = [
    "nomis-offender_bookings",
    "nomis-offender_external_movements",
    "nomis-offenders",
    "nomis-agency_locations",
    "nomis-offender_profile_details",
    "nomis-offender_identifiers",
    "nomis-profile_codes",
    "nomis-offender_health_problems",
    "nomis-reference_codes",
    "nomis-addresses",
    "nomis-address_usages",
    "nomis-offender_contact_persons",
    "nomis-offender_imprison_statuses",
    "nomis-imprisonment_statuses",
    "nomis-offender_sent_calculations",
    "nomis-offender_release_details",
    "nomis-movement_reasons",
    "nomis-offender_assessments",
    "nomis-assessments",
    "nomis-offender_sentences",
    "nomis-orders",
    "nomis-offender_iep_levels",
    "nomis-offender_cases",
    "nomis-court_events",
    "nomis-court_event_charges",
    "nomis-offence_result_codes",
    "nomis-offender_alerts",
    "nomis-offender_charges",
    "nomis-offences",
    "nomis-statutes",
    "nomis-offence_indicators",
    "nomis-offender_rehab_decisions",
    "nomis-offender_rehab_providers",
    "nomis-rehabilitation_providers",
    "nomis-agency_internal_locations",
    "nomis-areas",
]

DN_TABLES = {
    "prisons": None,
    "inc_response_flags": None,
    "assaults": ["inc_response_flags"],
    "assaults_detail": ["inc_response_flags"],
    "selfharm": ["inc_response_flags"],
    "selfharm_detail": ["inc_response_flags"],
    "sid_invol": ["inc_response_flags"],
    "disorder": ["inc_response_flags"],
    "finds": ["inc_response_flags"],
    "finds_detail": ["inc_response_flags"],
    "involvements": ["inc_response_flags"],
    "offender_location": ["inc_response_flags"],
    "current_pop": ["inc_response_flags", "offender_location"],
}


# A dictionary specifying irregular PK extractions
# and a list of days of month on which they are extracted
# (for prohibitvely large tables)
PK_EXCEPTIONS = {"11": [0]}
PK_EXTRACTIONS = {
    "1": ["OFFENDER_PROFILE_DETAILS"],
    "2": ["ORDERS", "OFFENDER_EXTERNAL_MOVEMENTS"],
    "3": ["OFFENDER_SENTENCE_CHARGES", "INCIDENT_CASE_RESPONSES"],
    "4": ["OFFENDER_ASSESSMENTS", "INCIDENT_CASE_QUESTIONS"],
    "5": ["ADDRESSES", "BED_ASSIGNMENT_HISTORIES"],
    "6": ["COURT_EVENT_CHARGES", "OFFENDER_ASSESSMENT_ITEMS"],
    "7": ["INCIDENT_CASE_PARTIES", "OFFENDER_SENTENCES", "PERSONS", "OFFENDER_VISITS"],
    "8": [
        "OFFENDER_BOOKINGS",
        "OFFENDER_SENT_CALCULATIONS",
        "COURT_EVENTS",
        "OFFENDER_CONTACT_PERSONS",
    ],
    "9": [
        "OFFENDER_ALERTS",
        "OFFENDER_SENTENCE_TERMS",
        "OFFENDER_IMPRISON_STATUSES",
        "OFFENDER_IEP_LEVELS",
    ],
    "10": [
        "OFFENDER_VISIT_VISITORS",
        "OFFENDER_PHYSICAL_ATTRIBUTES",
        "OFFENDER_CSIP_ATTENDEES",
        "OFFENDER_CSIP_FACTORS",
        "OFFENDER_CSIP_INTVW",
        "OFFENDER_CSIP_PLANS",
        "OFFENDER_CSIP_REPORTS",
        "OFFENDER_CSIP_REVIEWS",
    ],
    "11": ["OFFENDER_TRANSACTIONS"],
    "12": [
        "AGENCY_VISIT_TIMES",
        "OFFENDER_VISIT_ORDERS",
        "OFFENDER_RESTRICTIONS",
        "AGENCY_VISIT_SLOTS",
        "CORPORATES",
        "USER_ACCESSIBLE_CASELOADS",
        "CASELOAD_AGENCY_LOCATIONS",
        "OFFENDER_IND_SCHEDULES",
        "OFFENDER_VO_VISITORS",
    ],
    "0": [
        "OFFENDERS",
        "OFFENDER_CHARGES",
        "INCIDENT_CASES",
        "ADDRESS_USAGES",
        "OFFENDER_OIC_SANCTIONS",
        "OFFENDER_CASES",
        "OFFENDER_HEALTH_PROBLEMS",
        "OFFENDER_IDENTIFIERS",
        "OFFENDER_RELEASE_DETAILS",
        "OFFENDER_REHAB_DECISIONS",
        "AGENCY_INTERNAL_LOCATIONS",
        "OFFENDER_NA_DETAILS",
        "OFFENDER_NON_ASSOCIATIONS",
        "REFERENCE_CODES",
        "AGENCY_LOCATIONS",
        "PROFILE_CODES",
        "QUESTIONNAIRE_QUESTIONS",
        "QUESTIONNAIRE_ANSWERS",
        "QUESTIONNAIRES",
        "IMPRISONMENT_STATUSES",
        "INCIDENT_STATUSES",
        "OFFENCES",
        "QUESTIONNAIRE_ROLES",
        "ASSESSMENTS",
        "STATUTES",
        "MOVEMENT_REASONS",
        "OFFENCE_INDICATORS",
        "OFFENCE_RESULT_CODES",
        "AREAS",
        "OFFENDER_RISK_PREDICTORS",
        "GANG_NON_ASSOCIATIONS",
        "GANGS",
        "OFFENDER_GANG_AFFILIATIONS",
        "OFFENDER_GANG_EVIDENCES",
        "OFFENDER_GANG_INVESTS",
        "OFFENDER_PERSON_RESTRICTS",
        "STAFF_MEMBERS",
        "RANDOM_TESTING_PROGRAMS",
        "REHABILITATION_PROVIDERS",
        "OFFENDER_REHAB_PROVIDERS",
        "SENTENCE_CALC_TYPES",
        "PHONES",
        "INTERNET_ADDRESSES",
        "STAFF_USER_ACCOUNTS",
        "PROFILE_TYPES",
    ],
}

owner = "Managed Pipelines & Modernisation Team"
email = ["managedpipelinesandmodernisation@digital.justice.gov.uk"]
tags = ["nomis"]

