dag:
  repository: moj-analytical-services/airflow-sdt-extras
  tag: v1.2.4
  env_vars:
    AIRFLOW_ENVIRONMENT: "DEVELOPMENT" #to be changed to dev once we have a prod DAG running
  inlets:
    - "s3://alpha-app-safety-diagnostic-tool/development/"
  schedule:
    datasets:
      - "s3://alpha-app-safety-diagnostic-tool/development/"

iam:
  athena: write

  s3_read_only:
    - alpha-safety-mi/prisons_ds/*
    - alpha-viper/*
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_dn/*
    - mojap-derived-tables/seeds/nomis_dn/*

  s3_read_write:
    - alpha-app-safety-diagnostic-tool/*

notifications:
  emails:
    - sdt-support@justice.gov.uk

maintainers:
  - miller-william
  - lauratraceymoj

tags:
  business_unit: HMPPS
  owner: william.miller1@justice.gov.uk
