---
dag:
  repository: ministryofjustice/airflow-export-sop-to-idam
  tag: v3.0
  schedule: "0 10 * * *"
  env_vars:
    AWS_DEFAULT_REGION: "eu-west-2"

iam:
  s3_read_only:
    - mojap-data-production-shared-services-client-team-gov-29148/cgi-ssct-sop/*
    - mojap-land-preprod/corporate/report_extractor/fieldglass/MoJ_DMET_Corperate_Headcount_v2/
  kms:
    - arn:aws:kms:eu-west-2:593291632749:key/62503ba6-316e-473d-ae4b-042f8420dd07

secrets:
  - sharepoint-client-secret

notifications:
  slack_channel: dmet-corp-notifications

  emails:
    - William.Orr@justice.gov.uk
    - Supratik.Chowdhury@justice.gov.uk

maintainers:
  - moj-supratikc
  - williamorrie

tags:
  business_unit: Central Digital
  owner: William.Orr@justice.gov.uk
