---
dag:
  repository: moj-analytical-services/airflow-file
  tag: v0.0.21-test-8
  schedule: "0 8 1-3 * *"
  env_vars:
    AFFILE_PIPELINE_NAME: "po_sscl_details"
    AFFILE_ENV: "prod"
    AFFILE_SCHEMA_CONTRACT: "freeze"
    AWS_DEFAULT_REGION: "eu-west-1"
    AWS_ATHENA_QUERY_EXTRACT_REGION: "eu-west-1"
    AWS_DEFAULT_EXTRACT_REGION: "eu-west-1"
    AFFILE_ALLOW_PROD: true

  catchup: false
  max_active_runs: 1
  retries: 0
  compute_profile: general-on-demand-2vcpu-8gb

iam:
  athena: write
  glue: true

  s3_read_only:
    - mojap-land/corporate/report_extractor_prod/splashbi/*

  s3_read_write:
    - mojap-processed/domain__synergy/env__prod/synergy_grni/*
    - mojap-processed/domain__synergy/env__prod/synergy_grini_staging/*

notifications:
  slack_channel: dmet-corp-notifications

  emails:
    - mohammed.ahad1@justice.gov.uk
    - Supratik.Chowdhury@justice.gov.uk

maintainers:
  - morezwan
  - moj-supratikc

tags:
  business_unit: Central Digital
  owner: mohammed.ahad1@justice.gov.uk
