---
dag:
  repository: moj-analytical-services/airflow-file
  tag: v0.0.24-test-5
  schedule: "0 8 1-3 * *"
  env_vars:
    AFFILE_ENV: "prod"
    AFFILE_SCHEMA_CONTRACT: "evolve"
    AWS_DEFAULT_REGION: "eu-west-1"
    AWS_ATHENA_QUERY_EXTRACT_REGION: "eu-west-1"
    AWS_DEFAULT_EXTRACT_REGION: "eu-west-1"
    AFFILE_ALLOW_PROD: true

  catchup: false
  max_active_runs: 1
  retries: 0
  compute_profile: general-on-demand-8vcpu-32gb
  tasks:
    load-po_sscl_details:
      env_vars:
        AFFILE_PIPELINE_NAME: "po_sscl_details"
    load-supplier_headers:
      env_vars:
        AFFILE_PIPELINE_NAME: "supplier_headers"
    load-supplier_sites:
      env_vars:
        AFFILE_PIPELINE_NAME: "supplier_sites"
    load-customer_sites:
      env_vars:
        AFFILE_PIPELINE_NAME: "customer_sites"
    load-customer_headers:
      env_vars:
        AFFILE_PIPELINE_NAME: "customer_headers"
    load-sba_mo_locations:
      env_vars:
        AFFILE_PIPELINE_NAME: "sba_mo_locations"
    load-po_lines:
      env_vars:
        AFFILE_PIPELINE_NAME: "po_lines"
    load-po_headers:
      env_vars:
        AFFILE_PIPELINE_NAME: "po_headers"
    load-supplier_bank_accounts:
      env_vars:
        AFFILE_PIPELINE_NAME: "supplier_bank_accounts"

iam:
  athena: write
  glue: true

  s3_read_only:
    - mojap-land/corporate/report_extractor_prod/splashbi/*

  s3_read_write:
    - mojap-processed/domain__synergy/env__prod/synergy_grni/*
    - mojap-processed/domain__synergy/env__prod/synergy_grini_staging/*
    - mojap-processed/domain__synergy/env__prod/athena_query_dump/*
    - mojap-processed/domain__commercial/env__prod/synergy_sop/*
    - mojap-processed/domain__commercial/env__prod/synergy_sop_staging/*
    - mojap-processed/domain__commercial/env__prod/athena_query_dump/*

notifications:
  slack_channel: dmet-corp-splashbi-notifications

  emails:
    - mohammed.ahad1@justice.gov.uk
    - Supratik.Chowdhury@justice.gov.uk

maintainers:
  - morezwan
  - moj-supratikc

tags:
  business_unit: Central Digital
  owner: mohammed.ahad1@justice.gov.uk
