---
dag:
  repository: moj-analytical-services/airflow-avature-scraper
  tag: 0.0.17

iam:
  athena: write
  s3_read_write:
    - alpha-recruitment-data-model/avature-extracts/*
    - alpha-recruitment-data-model/avature-iceberg/*

notifications:
  slack_channel: dmet-corp-notifications

  emails:
    - Laurence.Droy@justice.gov.uk
    - william.orr@justice.gov.uk
    - Supratik.Chowdhury@justice.gov.uk

maintainers:
  - ltd-pa

tags:
  business_unit: Central Digital
  owner: Laurence.Droy@justice.gov.uk
