---
dag:
  repository: moj-analytical-services/airflow-file
  tag: v0.0.27-test-1
  env_vars:
    env: dev
  tasks:
    removed_cases_moj:
      env_vars:
        pipeline_name: removed_cases_moj
    appeals_hmpps:
      env_vars:
        pipeline_name: appeals_hmpps

iam:
  athena: write
  glue: true
  s3_read_only:
    - mojap-land/corporate/epm/*
  s3_read_write:
    - mojap-processed/domain__hr/env__dev/epm_dev/*
    - mojap-processed/domain__hr/env__dev/epm_dev_staging/*

notifications:
  slack_channel: dmet-corp-notifications

  emails:
    - Laurence.Droy@justice.gov.uk
    - William.Orr@justice.gov.uk
    - Supratik.Chowdhury@justice.gov.uk

maintainers:
  - ltd-pa
  - williamorrie
  - moj-supratikc

tags:
  business_unit: Central Digital
  owner: william.orr@justice.gov.uk
