---
dag:
  repository: moj-analytical-services/airflow-export-em-data-p1
  tag: v1.0.1-rc
  compute_profile: gpu-spot-8vcpu-32gb
  catchup: false
  depends_on_past: false
  start_date: "2024-01-01"
  schedule: "0 7 * * *"
  max_active_runs: 1
  env_vars:
    START_DATE: "2024-01-01"
    END_DATE: "{{ data_interval_end }}"
    AWS_DEFAULT_REGION: "eu-west-2"
    AWS_ATHENA_QUERY_EXTRACT_REGION: "eu-west-2"
    AWS_DEFAULT_EXTRACT_REGION: "eu-west-2"

notifications:
  emails:
    - matt.heery@justice.gov.uk
  slack_channel: em-engineers-moj-madetech

iam:
  external_role: arn:aws:iam::976799291502:role/airflow-prod-export-em-data-p1

maintainers:
  - matt-heery
  - mrixson-moj
  - kraihanmoj
  - lucy-astley-jones

tags:
  business_unit: HMPPS
  owner: EMDataEngineering@justice.gov.uk
