---
dag:
  repository: moj-analytical-services/mbpr-airflow-pipelines
  tag: v1.1.2
  env_vars:
    MODE: "smart-survey"

maintainers:
  - mikeAdamsMOJ
  - calumabarnett

iam:
  s3_read_write:
    - alpha-mission-brilliant-performance-reporting/*

secrets:
  - api-auth

tags:
  business_unit: Central Digital
  owner: Calum.Barnett@justice.gov.uk
