dag:
  repository: moj-analytical-services/airflow-sdp-extraction
  tag: v4.2.2
  start_date: "2026-09-23"
  schedule: 30 2 * * *
  retries: 0
  hmcts_sdp_networking: True
  max_active_runs: 1
  env_vars:
    TASK: "extract"
    LOG_LEVEL: "INFO"
    ENDPOINT: "MI_PERSISTENT_PROD"
    SDP_TABLE_PREFIX: "v3-ccd"
    PRESERVE_SDP_FOLDER_STRUCT: "replace_prefix"
    COPY_MODE: "new"
    CHECK_MODE: "table"
    FILENAME_COL_NAME: "meta__source_file"
    EXCLUDED_FILES_REGEXPR: "_metadata.json$"
    DATABASE_NAME: "ccd_public_private_law"
    LAND_BUCKET: "s3://mojap-land"
    HIST_BUCKET: "s3://mojap-raw-hist"
    LAND_FOLDER: "hmcts/ccd-public-private-law"
    HIST_FOLDER: "hmcts/ccd-public-private-law"
    CUT_OFF: "2023-01-01"
  tasks:
    ccd_extract_privatelaw_privatelaw_exceptionrecord:
      env_vars:
        TABLE_NAME: "privatelaw-privatelaw-exceptionrecord"
        S3_TABLE_NAME: "privatelaw_privatelaw_exceptionrecord"
        FILENAME_TABLE_NAME: "privatelaw_privatelaw_exceptionrecord"
    ccd_extract_privatelaw_prlapps:
      env_vars:
        TABLE_NAME: "privatelaw-prlapps"
        S3_TABLE_NAME: "privatelaw_prlapps"
        FILENAME_TABLE_NAME: "privatelaw_prlapps"
    ccd_extract_privatelaw_prlapps_all_cols:
      env_vars:
        TABLE_NAME: "privatelaw-prlapps-all-cols"
        S3_TABLE_NAME: "privatelaw_prlapps_all_cols"
        FILENAME_TABLE_NAME: "privatelaw_prlapps_all_cols"
    ccd_extract_publiclaw_care_supervision_epo:
      env_vars:
        TABLE_NAME: "publiclaw-care-supervision-epo"
        S3_TABLE_NAME: "publiclaw_care_supervision_epo"
        FILENAME_TABLE_NAME: "publiclaw_care_supervision_epo"
    ccd_extract_publiclaw_care_supervision_epo_all_cols:
      env_vars:
        TABLE_NAME: "publiclaw-care-supervision-epo-all-cols"
        S3_TABLE_NAME: "publiclaw_care_supervision_epo_all_cols"
        FILENAME_TABLE_NAME: "publiclaw_care_supervision_epo_all_cols"
    ccd_extract_publiclaw_publiclaw_exceptionrecord:
      env_vars:
        TABLE_NAME: "publiclaw-publiclaw-exceptionrecord"
        S3_TABLE_NAME: "publiclaw_publiclaw_exceptionrecord"
        FILENAME_TABLE_NAME: "publiclaw_publiclaw_exceptionrecord"

iam:
  athena: write
  s3_read_write:
    - mojap-land/hmcts/ccd-public-private-law/*
    - mojap-raw-hist/hmcts/ccd-public-private-law/*
  s3_read_only:
    - alpha-mojap-ccd/public-private-law/*

secrets:
  - sdp-pass

notifications:
  slack_channel: dmet-hmcts-notifications

maintainers:
  - Andy-Cook
  - DanJ-MOJ
  - AntonyJScott

tags:
  business_unit: Central Digital
  owner: cft_data_engineering@justice.gov.uk
