---
dag:
  repository: moj-analytical-services/airflow-occupeye-scraper
  tag: v2.0.4
  python_dag: true

iam:
  athena: write
  glue: true
  s3_read_write:
    - alpha-dag-occupeye/*
    - alpha-app-occupeye-automation/*
    - mojap-athena-query-dump/*

maintainers:
  - ltd-pa
  - williamorrie
  - moj-supratikc

tags:
  business_unit: Central Digital
  owner: Laurence.Droy@justice.gov.uk
