---
dag:
  repository: moj-analytical-services/airflow-occupeye-scraper
<<<<<<< HEAD
  tag: v2.1.6
=======
  tag: v2.1.5
>>>>>>> origin/main
  python_dag: true

iam:
  athena: write
  glue: true
  s3_read_write:
    - alpha-dag-occupeye/*
    - alpha-app-occupeye-automation/*
    - mojap-athena-query-dump/*

maintainers:
  - ltd-pa
  - benjamin-finucane

tags:
  business_unit: Central Digital
  owner: Laurence.Droy@justice.gov.uk
