---
dag:
  repository: ministryofjustice/analytical-platform-airflow-cadet-deployer
  tag: 1.1.26
  compute_profile: general-on-demand-32vcpu-128gb
  schedule: "0 12 * * 1-6"
  catchup: false
  outlets:
    - "s3://mojap-derived-tables/prod/daily/"
  env_vars:
    DEPLOY_ENV: sandpit
    DBT_PROFILE_WORKGROUP: dbt-daily
    DBT_PROJECT: mojap_derived_tables
    WORKFLOW_NAME: deploy-daily
    DBT_SELECT_CRITERIA: tag:daily
    BRANCH: main
    MODE: build

maintainers:
  - jhpyke

secrets:
  - github-key

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/prod/*

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
