---
dag:
  repository: moj-analytical-services/airflow-clean-temp-dbs
  tag: v0.3.0


maintainers:
  - Thomas-Hirsch

iam:
  athena: write
  s3_read_write:
    - mojap-athena-query-dump/*

tags:
  business_unit: HQ
  owner: thomas.hirsch@justice.gov.uk
