dag:
  repository: ministryofjustice/aws-sharepoint-connector
  tag: test-airflow
  catchup: false
  depends_on_past: false
  is_paused_upon_creation: false
  max_active_runs: 4
  retries: 1
  retry_delay: 150
  start_date: "2026-01-01"
  schedule: None
  tasks:
    move_file:
      compute_profile: "general-on-demand-4vcpu-16gb"
      env_vars:
        S3_BUCKET: "alpha-opg-etl"
        SP_SITE: "OPGDataCatalogue"
        SP_LIBRARY: "Shared Documents"
iam:
  s3_read_write:
    - alpha-opg-etl/*

secrets:
  - azure-client-secret
  - azure-tenant-id
  - azure-client-id

maintainers:
  - p-sin

tags:
  business_unit: OPG
  owner: philip.sinfield@justice.gov.uk
