---
dag:
  repository: moj-analytical-services/airflow-report-extractor
  tag: v0.0.17
  python_dag: True

iam:
  s3_read_write:
    - mojap-land/corporate/report_extractor_prod/splashbi/*

secrets:
  - splashbi-credentials

notifications:
  slack_channel: dmet-corp-notifications
  emails:
    - william.orr@justice.gov.uk
    - Supratik.Chowdhury@justice.gov.uk
    - mohammed.ahad1@justice.gov.uk

maintainers:
  - williamorrie
  - moj-supratikc
  - morezwan

tags:
  business_unit: Central Digital
  owner: supratik.chowdhury@justice.gov.uk
