---
dag:
  repository: moj-analytical-services/airflow-report-extractor
  tag: v0.0.16-test-grni
  schedule: "0 7 1-7 * MON"
  env_vars:
    REPORT_APP: "splashbi"
    REPORT_RUNTIME_ENV: "prod"
    REPORT_RUN_MODE: "trigger"
  tasks:
    po_sscl_details:
      env_vars:
        REPORT_NAME: "po_sscl_details"


iam:
  s3_read_write:
    - mojap-land/corporate/report_extractor_prod/splashbi/*

secrets:
  - splashbi-credentials

notifications:
  slack_channel: dmet-corp-notifications

  emails:
    - william.orr@justice.gov.uk
    - Supratik.Chowdhury@justice.gov.uk
    - mohammed.ahad1@justice.gov.uk

maintainers:
  - williamorrie
  - moj-supratikc
  - morezwan

tags:
  business_unit: Central Digital
  owner: supratik.chowdhury@justice.gov.uk
