---
tags:
  business_unit: HQ
  owner: analytical-platform@justice.gov.uk

dag:
  repository: ministryofjustice/analytical-platform-airflow-poc-workflow
  tag: 0.0.6

maintainers:
  - jacobwoffenden
  - julialawrence
