---
dag:
  repository: moj-analytical-services/analytical-platform-airflow-python-example
  tag: 2.4.0

notifications:
  emails:
    - jacob.woffenden@justice.gov.uk
  slack_channel: analytical-platform-airflow-testing

maintainers:
  - jacobwoffenden
  - jhpyke

iam:
  s3_read_write:
    - alpha-everyone/airflow-example/*
    - arn:aws:s3:::alpha-everyone/airflow-should-fail/*
  kms:
    - im-not-a-key

secrets:
  - api-key
  - user
  - password

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
