---
tags:
  application: Analytical Platform
  business_unit: HQ
  owner: analytical-platform@justice.gov.uk

dag:
  repository: moj-analytical-services/analytical-platform-airflow-python-example
  tag: 1.0.2
