---
dag:
  repository: moj-analytical-services/analytical-platform-airflow-python-example
  tag: 2.0.0
  compute_profile: gpu-spot-8vcpu-32gb
  env_vars:
    MODE: "benchmark"

iam:
  # athena: write
  # bedrock: true
  # glue: true
  kms:
    - arn:aws:kms:eu-west-2:123456789012:key/mrk-12345678909876543212345678909876
  s3_deny:
    - mojap-compute-development-dummy/deny1/*
    - mojap-compute-development-dummy/deny2/*
  s3_read_only:
    - mojap-compute-development-dummy/readonly1/*
    - mojap-compute-development-dummy/readonly2/*
  s3_read_write:
    - mojap-compute-development-dummy/readwrite1/*
    - mojap-compute-development-dummy/readwrite2/*
  s3_write_only:
    - mojap-compute-development-dummy/writeonly1/*
    - mojap-compute-development-dummy/writeonly2/*

maintainers:
  - jacobwoffenden
  - julialawrence

secrets:
  - api-key

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
