---
dag:
  repository: moj-analytical-services/analytical-platform-airflow-python-example
  tag: 2.14.0
  params:
    example_param: underscored
  env_vars:
    DAG_RUN_ID: "{{ run_id }}"

notifications:
  emails:
    - jacob.woffenden@justice.gov.uk
  slack_channel: analytical-platform-airflow-testing

iam:
  cloudwatch_logs_read_only:
    - arn:aws:logs:eu-west-2:593291632749:log-group:cloudtrail-athena-events:*

maintainers:
  - jacobwoffenden
  - jhpyke
  - gary-h9

secrets:
  - api-key
  - user
  - password

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk

# Trivial change to workflow to trigger workflow-validation action.
