---
tags:
  business_unit: HQ
  owner: analytical-platform@justice.gov.uk

dag:
  repository: moj-analytical-services/analytical-platform-airflow-python-example
  tag: 1.2.0
  compute_profile: gpu-spot-8vcpu-32gb

iam:
  bedrock: true
  kms:
    - arn:aws:kms:eu-west-2:123456789012:key/mrk-12345678909876543212345678909876
  s3_read_only:
    - mojap-compute-development-dummy/readonly1/*
    - mojap-compute-development-dummy/readonly2/*
  s3_read_write:
    - mojap-compute-development-dummy/readwrite1/*
    - mojap-compute-development-dummy/readwrite2/*

maintainers:
  - jacobwoffenden
  - julialawrence

secrets:
  - username
  - password
  - api-key
