---
tags:
  application: Analytical Platform
  business_unit: HQ
  owner: analytical-platform@justice.gov.uk

dag:
  repository: ministryofjustice/analytical-platform-airflow-poc-workflow
  tag: 0.0.6
  compute_profile: general-spot-1vcpu-4gb
