dag:
  repository: moj-analytical-services/hmcts-dlt-pipeline
  tag: v1.0.2
  retries: 1
  retry_delay: 150
  max_active_runs: 3
  hmcts_sdp_networking: true
  env_vars:
    AWS_DEFAULT_REGION: "eu-west-1"
    DESTINATION_PATH: "s3://mojap-land-dev/hmcts/libre/"
    ATHENA_DATABASE_NAME: "libre_v3_prod"

  tasks:
    process-v3-cgi-libra-addresses:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-addresses"

    process-v3-cgi-libra-business-type-facilities:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-business-type-facilities"

    process-v3-cgi-libra-business-types:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-business-types"

    process-v3-cgi-libra-business-unit-types:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-business-unit-types"

    process-v3-cgi-libra-business-units:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-business-units"

    process-v3-cgi-libra-case-defendants:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-case-defendants"

    process-v3-cgi-libra-case-entity-roles:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-case-entity-roles"

    process-v3-cgi-libra-case-flag-types:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-case-flag-types"

    process-v3-cgi-libra-case-management-rep-units:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-case-management-rep-units"

    process-v3-cgi-libra-case-management-units:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-case-management-units"

    process-v3-cgi-libra-case-offence-hearings:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-case-offence-hearings"

    process-v3-cgi-libra-case-offence-results-t:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-case-offence-results-t"

    process-v3-cgi-libra-case-offences:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-case-offences"

    process-v3-cgi-libra-cases:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-cases"

    process-v3-cgi-libra-cg-ref-codes:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-cg-ref-codes"

    process-v3-cgi-libra-co-result-term-responses:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-co-result-term-responses"

    process-v3-cgi-libra-co-terminal-responses:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-co-terminal-responses"

    process-v3-cgi-libra-commission-areas:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-commission-areas"

    process-v3-cgi-libra-court-houses:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-court-houses"

    process-v3-cgi-libra-court-room-types:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-court-room-types"

    process-v3-cgi-libra-court-rooms:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-court-rooms"

    process-v3-cgi-libra-defendants:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-defendants"

    process-v3-cgi-libra-diary-management-units:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-diary-management-units"

    process-v3-cgi-libra-diary-template-sessions:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-diary-template-sessions"

    process-v3-cgi-libra-document-set-headers:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-document-set-headers"

    process-v3-cgi-libra-driver-details:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-driver-details"

    process-v3-cgi-libra-enforcement-account-types:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-enforcement-account-types"

    process-v3-cgi-libra-enforcement-headers:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-enforcement-headers"

    process-v3-cgi-libra-enforcement-report-headers:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-enforcement-report-headers"

    process-v3-cgi-libra-enforcer-allocations:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-enforcer-allocations"

    process-v3-cgi-libra-entity-nationalities:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-entity-nationalities"

    process-v3-cgi-libra-entity-roles:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-entity-roles"

    process-v3-cgi-libra-facilities:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-facilities"

    process-v3-cgi-libra-functional-areas:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-functional-areas"

    process-v3-cgi-libra-hearing-entity-roles:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-hearing-entity-roles"

    process-v3-cgi-libra-hearings-all:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-hearings-all"

    process-v3-cgi-libra-joint-charge-links:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-joint-charge-links"

    process-v3-cgi-libra-joint-charges:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-joint-charges"

    process-v3-cgi-libra-judiciaries:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-judiciaries"

    process-v3-cgi-libra-judiciary-assignments:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-judiciary-assignments"

    process-v3-cgi-libra-legal-advisors:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-legal-advisors"

    process-v3-cgi-libra-link-addresses:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-link-addresses"

    process-v3-cgi-libra-location-facilities:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-location-facilities"

    process-v3-cgi-libra-locations:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-locations"

    process-v3-cgi-libra-mag-court-committees:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-mag-court-committees"

    process-v3-cgi-libra-map-offence-type:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-map-offence-type"

    process-v3-cgi-libra-names:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-names"

    process-v3-cgi-libra-national-court-houses:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-national-court-houses"

    process-v3-cgi-libra-nationalities:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-nationalities"

    process-v3-cgi-libra-notes:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-notes"

    process-v3-cgi-libra-occupations:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-occupations"

    process-v3-cgi-libra-offence-acts-and-sections:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-offence-acts-and-sections"

    process-v3-cgi-libra-offence-headers:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-offence-headers"

    process-v3-cgi-libra-offence-revisions:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-offence-revisions"

    process-v3-cgi-libra-offence-statements-of-fact:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-offence-statements-of-fact"

    process-v3-cgi-libra-offence-terminal-entries:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-offence-terminal-entries"

    process-v3-cgi-libra-offence-wordings:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-offence-wordings"

    process-v3-cgi-libra-organisation-names:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-organisation-names"

    process-v3-cgi-libra-organisations:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-organisations"

    process-v3-cgi-libra-panel-types:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-panel-types"

    process-v3-cgi-libra-panels:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-panels"

    process-v3-cgi-libra-persons:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-persons"

    process-v3-cgi-libra-petty-sessional-areas:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-petty-sessional-areas"

    process-v3-cgi-libra-plea-types:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-plea-types"

    process-v3-cgi-libra-pleas:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-pleas"

    process-v3-cgi-libra-police-force-codes:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-police-force-codes"

    process-v3-cgi-libra-reasons:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-reasons"

    process-v3-cgi-libra-result-code-groups:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-result-code-groups"

    process-v3-cgi-libra-result-groups:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-result-groups"

    process-v3-cgi-libra-result-headers:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-result-headers"

    process-v3-cgi-libra-result-report-headers:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-result-report-headers"

    process-v3-cgi-libra-result-revisions:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-result-revisions"

    process-v3-cgi-libra-result-sets:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-result-sets"

    process-v3-cgi-libra-result-terminal-entries:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-result-terminal-entries"

    process-v3-cgi-libra-role-case-types:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-role-case-types"

    process-v3-cgi-libra-roles:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-roles"

    process-v3-cgi-libra-rte-element-definitions:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-rte-element-definitions"

    process-v3-cgi-libra-rte-menu-option-elements:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-rte-menu-option-elements"

    process-v3-cgi-libra-rte-menu-options:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-rte-menu-options"

    process-v3-cgi-libra-rte-menus:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-rte-menus"

    process-v3-cgi-libra-rtr-application-details:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-rtr-application-details"

    process-v3-cgi-libra-rtr-application-offences:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-rtr-application-offences"

    process-v3-cgi-libra-rtr-applications:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-rtr-applications"

    process-v3-cgi-libra-rtr-reasons:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-rtr-reasons"

    process-v3-cgi-libra-session-blocks:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-session-blocks"

    process-v3-cgi-libra-sessions:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-sessions"

    process-v3-cgi-libra-solicitors:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-solicitors"

    process-v3-cgi-libra-standard-informants:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-standard-informants"

    process-v3-cgi-libra-supp-documents:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-supp-documents"

    process-v3-cgi-libra-supplementary-items:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-supplementary-items"

    process-v3-cgi-libra-suppress-overrides:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-suppress-overrides"

    process-v3-cgi-libra-tvlo-headers:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-tvlo-headers"

    process-v3-cgi-libra-vehicle-links:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-vehicle-links"

    process-v3-cgi-libra-vehicles:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libra-vehicles"
    
    process-v3-cgi-libraapp-app-list-entry-fee-id:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libraapp-app-list-entry-fee-id"

    process-v3-cgi-libraapp-app-list-entry-fee-status:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libraapp-app-list-entry-fee-status"

    process-v3-cgi-libraapp-app-list-entry-official:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libraapp-app-list-entry-official"

    process-v3-cgi-libraapp-app-list-entry-resolutions:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libraapp-app-list-entry-resolutions"

    process-v3-cgi-libraapp-application-codes:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libraapp-application-codes"

    process-v3-cgi-libraapp-application-list-entries:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libraapp-application-list-entries"

    process-v3-cgi-libraapp-application-lists:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libraapp-application-lists"

    process-v3-cgi-libraapp-application-register:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libraapp-application-register"

    process-v3-cgi-libraapp-criminal-justice-area:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libraapp-criminal-justice-area"

    process-v3-cgi-libraapp-fee:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libraapp-fee"

    process-v3-cgi-libraapp-name-address:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libraapp-name-address"

    process-v3-cgi-libraapp-resolution-codes:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libraapp-resolution-codes"

    process-v3-cgi-libraapp-standard-applicants:
      env_vars:
        CONTAINER_NAME: "v3-cgi-libraapp-standard-applicants"

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-land-dev/hmcts/libre/*

secrets:
  - pds

notifications:
  slack_channel: dmet-hmcts-notifications

maintainers:
  - jovita-brundziene
  - Andy-Cook

tags:
  business_unit: Central Digital
  owner: jovita.brundziene@justice.gov.uk
