---
dag:
  repository: moj-analytical-services/airflow-file
  tag: v0.0.21-test-14
  schedule: "30 8 * * 1-5"
  is_paused_upon_creation: true
  env_vars:
    AFFILE_PIPELINE_NAME: "sop__iexp01_expenses_live"
    AFFILE_ENV: "prod"
    AFFILE_SCHEMA_CONTRACT: "freeze"
    AWS_DEFAULT_REGION: "eu-west-1"
    AWS_ATHENA_QUERY_EXTRACT_REGION: "eu-west-1"
    AWS_DEFAULT_EXTRACT_REGION: "eu-west-1"
    AFFILE_ALLOW_PROD: "true"
  catchup: false
  max_active_runs: 1
  retries: 0
  compute_profile: general-on-demand-2vcpu-8gb

iam:
  athena: write
  glue: true

  s3_read_only:
    - mojap-land/corporate/report_extractor_prod/splashbi/*

  s3_read_write:
    - mojap-processed/domain__hr/env__prod/corporate_sop_prod/*
    - mojap-processed/domain__hr/env__prod/corporate_sop_prod_staging/*
    - mojap-processed/corporate/sop/prod/*
    - mojap-processed/domain__hr/env__prod/athena_query_dump/*

notifications:
  slack_channel: dmet-corp-notifications

  emails:
    - Laurence.Droy@justice.gov.uk
    - William.Orr@justice.gov.uk
    - Supratik.Chowdhury@justice.gov.uk

maintainers:
  - ltd-pa
  - williamorrie
  - moj-supratikc

tags:
  business_unit: Central Digital
  owner: Laurence.Droy@justice.gov.uk
