---
dag:
  repository: moj-analytical-services/laa-search-index-airflow-source
  tag: v0.1.7

maintainers:
  - nina-knowles-justice
  - dami-moj

secrets:
  - bucket
  - key

tags:
  business_unit: LAA
  owner: LAA-Data-Engineering@justice.gov.uk
