---
dag:
  repository: ministryofjustice/analytical-platform-airflow-cadet-deployer
  tag: 1.4.2-dpr-daily-3
  compute_profile: general-on-demand-8vcpu-32gb
  schedule: "0 5 * * MON-FRI"
  start_date: "2026-08-17"
  catchup: false
  env_vars:
    DEPLOY_ENV: prod_dev
    DBT_PROJECT: hmpps_digital_prisons_reporting_tables
    S3_BUCKET: dpr-structured-historical-production
    WORKFLOW_NAME: deploy-prod-dev-digital-prisons-reporting
    DBT_PROFILE_WORKGROUP: analytics-generic-athena-workgroup
    DBT_SELECT_CRITERIA: "tag:dpr-daily"
    MODE: build
    AWS_DEFAULT_REGION: eu-west-2
    DBT_PROFILE: dpr
    ENFORCE_LAKE_FORMATION: true
    RUN_SOURCE_FRESHNESS: true
    RUN_UNIT_TESTS: false
    FULL_REFRESH: false
    CHECK_DUAL_MATERIALIZATION: true
    DEPLOY_MODIFIED_SEEDS: true
secrets:
  - github-key

maintainers:
  - andrewc-moj

notifications:
  emails:
    - andrew.craik@justice.gov.uk
    - anthony.fitzroy@justice.gov.uk
    - anthony.cody@justice.gov.uk

iam:
  external_role: arn:aws:iam::004723187462:role/dpr-data-api-cross-account-role

tags:
  business_unit: HMPPS
  owner: anthony.fitzroy@justice.gov.uk
