---
dag:
  repository: ministryofjustice/airflow-sp-poc
  tag: v1.0.15-dev

  env_vars:
    BUCKET: alpha-sp-poc
    S3_KEY: test_file.csv
    SP_LIBRARY_NAME: Account\ Management
    SP_UPLOAD_PATH: Probation\ Account\ Management/PRP\ Archive/Priya_test/

iam:
  s3_read_only:
    - alpha-sp-poc/*

secrets:
  - azure-tenant-id
  - azure-client-id
  - azure-client-secret
  - site-id

maintainers:
  - guyvw1

tags:
  business_unit: Central Digital
  owner: guy.wheeler@justice.gov.uk
