---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-secret.labels" . | nindent 4 }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: {{ .Values.secretStoreRefKind }}
    name: {{ .Values.secretStoreRefName }}
  target:
    name: {{ .Values.targetName }}
    deletePolicy: {{ .Values.deletePolicy }}
  data:
    - secretKey: {{ .Values.secretKey }}
      remoteRef:
        key: {{ .Values.remoteRefKey }}
