---
dag:
  repository: ministryofjustice/analytical-platform-airflow-cadet-deployer
  tag: 1.2.5
  schedule: "s3://mojap-derived-tables/prod/curated-daily/"
  catchup: false
  env_vars:
    DEPLOY_ENV: sandpit
    DBT_PROFILE_WORKGROUP: dbt-bold-daily-prod
    DBT_PROJECT: mojap_derived_tables
    WORKFLOW_NAME: bold-daily
    DBT_SELECT_CRITERIA: tag:bold_daily
    BRANCH: main
    MODE: build
  tasks:
    table_deploy:
      compute_profile: general-on-demand-8vcpu-32gb
      outlets:
        - "s3://mojap-derived-tables/prod/bold-daily"

maintainers:
  - jhpyke

secrets:
  - github-key

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/prod/*
    - alpha-bold-data-shares/reducing-reoffending/essex-police/pnc-id-extraction/sandpit/*

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
