dag:
  repository: moj-analytical-services/CourtCaseLoad
  tag: v.1.0.9

maintainers:
  - fogunpola

tags:
  business_unit: HMCTS
  owner: "flo.ogunpola@justice.gov.uk"  

#tasks:
#    - name: execute_notebook
#      operator: PapermillOperator
#      input_notebook: "/court_caseload_wb.ipynb" 
#      output_notebook: "/tmp/notebook_output.ipynb"

