dag:
  repository: moj-analytical-services/CourtCaseLoad
  tag: v1.0.4 
  tasks:
    task_id: execute_notebook
    operator: PapermillOperator
    input_notebook: "/court_caseload_wb.ipynb"  # Full path to notebook
    output_notebook: "/tmp/notebook_output.ipynb"  # Output location (ensure it's writable)

maintainers:
  - fogunpola

tags:
  business_unit: HMCTS
  owner: "flo.ogunpola@justice.gov.uk"  

 

