dag:
  repository: moj-analytical-services/CourtCaseLoad
  tag: v1.0.4 

maintainers:
  - fogunpola

tags:
  business_unit: HMCTS
  owner: "flo.ogunpola@justice.gov.uk"  

tasks:
    task_id: execute_notebook
    operator: PapermillOperator
    input_notebook: "/court_caseload_wb.ipynb" 
    output_notebook: "/tmp/notebook_output.ipynb"

