---
dag:
  repository: moj-analytical-services/airflow-bold-case-info-dashboard
  tag: v1.0.69-dev

  env_vars:
    AIRFLOW_TASK: lao_audit
    R_CONFIG_ACTIVE: prod

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-delius-prod/delius/*
    - mojap-delius-prod/live/tables/*
    - mojap-derived-tables/prod/models/domain_name=probation/database_name=delius/*
    - mojap-derived-tables/prod/models/domain_name=bold/database_name=bold_rr_essex_police_data/*
    - alpha-bold-rr-case-info-dashboard-usage/audit/prod/*

secrets:
  - cid-notify-api-key-prod
  - audit-key-password-prod

maintainers:
  - guyvw1

tags:
  business_unit: Central Digital
  owner: guy.wheeler@justice.gov.uk