dag:
  repository: moj-analytical-services/airflow-dmet-property
  tag: archive_metadata_custom_release_v.01
  compute_profile: "general-on-demand-1vcpu-4gb"

maintainers:
  - jnayak-moj

secrets:
  - api-key

iam:
  s3_read_write:
    - s3://mojap-land-dev/property/cde/*

tags:
  business_unit: property
  owner: jyotiranjan.nayak@justice.gov.uk
