---
dag:
  repository: moj-analytical-services/laa-search-index-airflow-search
  tag: v0.1.6

iam:
  s3_read_write:
    - laa-splink-search-s3/*
    - laa-splink-search-output/*
    - laa-splink-search-input/*

  s3_write_only:
    - laa-search-audit/*

  kms:
    - arn:aws:kms:eu-west-2:593291632749:key/c0f20b2d-7b3e-4a60-9c04-2fb3befe6a3f # To be Updated

maintainers:
  - nina-knowles-justice
  - dami-moj
  - jh-justice-dev
  - jfjb-justice

secrets:
  - source-request-bucket
  - source-request-key
  - source-output-bucket
  - source-output-key
  - audit-bucket
  - splink-bucket

tags:
  business_unit: LAA
  owner: LAA-Data-Engineering@justice.gov.uk
