dag:
  repository: moj-analytical-services/airflow-opg-etl
  tag: v3.2.0-test-1
  catchup: false
  depends_on_past: false
  is_paused_upon_creation: false
  max_active_runs: 4
  retries: 1
  retry_delay: 150
  schedule: "00 05 * * *"
  start_date: "2025-04-30"
  env_vars:
    DATABASE: "sirius"
    DATABASE_VERSION: "prod"
    GITHUB_TAG: {tag}
    ATHENA_DB_PREFIX: "opg"
    IAM_ROLE: "airflow_prod_opg_sirius"
    START_DATE: {start_date}
    AWS_DEFAULT_REGION: "eu-west-1"
    AWS_METADATA_SERVICE_TIMEOUT: "60"
    AWS_METADATA_SERVICE_NUM_ATTEMPTS: "5"

  tasks:
    to_land:
      env_vars:
        STEP: "to_land"
      compute_profile: "general-on-demand-1vcpu-4gb"
    land_to_raw_init:
      env_vars:
        STEP: "land_to_raw"
      compute_profile: "general-on-demand-1vcpu-4gb"
      dependencies: [to_land]
    land_to_raw:
      env_vars:
        STEP: "land_to_raw"
      compute_profile: "general-on-demand-1vcpu-4gb"
      dependencies: [land_to_raw_init]
    land_to_raw_close:
      env_vars:
        STEP: "land_to_raw"
      compute_profile: "general-on-demand-1vcpu-4gb"
      dependencies: [land_to_raw]
    raw_to_curated:
      env_vars:
        STEP: "raw_to_curated"
      compute_profile: "general-on-demand-1vcpu-4gb"
      dependencies: [land_to_raw_close]
    create_curated_database:
      env_vars:
        STEP: "create_curated_database"
      compute_profile: "general-on-demand-1vcpu-4gb"
      dependencies: [raw_to_curated]
    create_derived:
      env_vars:
        STEP: "create_derived"
      compute_profile: "general-on-demand-1vcpu-4gb"
      dependencies: [raw_to_curated, create_curated_database]

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-land-dev/opg/dev/sirius/*
    - mojap-raw/opg/dev/sirius/*
    - alpha-opg-etl/dev/sirius/*
    - mojap-athena-query-dump/*-airflow_dev_opg_sirius/*

  s3_read_only:
      - mojap-land-dev/opg/sirius/*
      - alpha-opg-etl/dev/nspl_reference/curated/*
      - alpha-opg-mi-dashboard/working/*

maintainers:
  - p-sin
  - gwionap

tags:
  business_unit: OPG
  owner: philip.sinfield@justice.gov.uk

notifications:
  emails:
    - philip.sinfield@justice.gov.uk
  slack_channel: opg-deds
