---
dag:
  repository: moj-analytical-services/laa-search-index-airflow-s3-ops
  tag: v0.2.2

  retries: 1
  max_active_runs: 1
  compute_profile: general-spot-1vcpu-4gb

  env_vars:
    AWS_REGION: "eu-west-2"
    LOG_LEVEL: "INFO"
    KMS_KEY_ARN: "arn:aws:kms:eu-west-2:593291632749:key/e22c7aa4-4469-4c69-a7ee-0708201c51c9"

  tasks:
    exists:
      env_vars:
        MODE: "exists"
        S3_PATH: "s3://mojap-data-production-datasync-laa-ingress-production/analysis_outputs/splink-with-collections/final_splink_collections_30_06_26.parquet"

    copy:
      dependencies: [exists]
      env_vars:
        MODE: "copy"
        S3_SOURCE: "s3://mojap-data-production-datasync-laa-ingress-production/analysis_outputs/splink-with-collections/final_splink_collections_30_06_26.parquet"
        S3_DESTINATION: "s3://laa-splink-search-s3/final_splink_collections_30_06_26.parquet"

    verify:
      dependencies: [copy]
      env_vars:
        MODE: "exists"
        S3_PATH: "s3://laa-splink-search-s3/"

iam:
  kms:
    - arn:aws:kms:eu-west-2:593291632749:key/fe4674f4-52dc-4b73-a7c5-259c282742ba
    - arn:aws:kms:eu-west-2:593291632749:key/e22c7aa4-4469-4c69-a7ee-0708201c51c9

  s3_read_write:
    - mojap-data-production-datasync-laa-ingress-production/analysis_outputs/*
    - laa-splink-search-s3/*

maintainers:
  - dami-moj

notifications:
  emails:
    - Damilola.Oyebade@justice.gov.uk
  slack_channel: laa-search-index-alerts

tags:
  business_unit: LAA
  owner: LAA-Data-Engineering@justice.gov.uk
