---
dag:
  repository: ministryofjustice/analytical-platform-airflow-cadet-deployer
  tag: 1.3.3
  schedule: None
  catchup: false
  env_vars:
    DEPLOY_ENV: prod
    DBT_PROFILE_WORKGROUP: dbt-curated-daily
    DBT_PROJECT: mojap_derived_tables
    WORKFLOW_NAME: deploy-curated-daily
    DBT_SELECT_CRITERIA: tag:curated-re-run-fix
    BRANCH: re-run-curated-fix
    MODE: build
  tasks:
    table_deploy:
      compute_profile: general-on-demand-8vcpu-32gb
      outlets:
        - "s3://mojap-derived-tables/prod/curated-daily/"

maintainers:
  - jhpyke
  - lalithanagarur

secrets:
  - github-key

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/prod/*

notifications:
  emails:
    - lalitha.nagarur3@justice.gov.uk
  slack_channel: de-probation-airflow-prod

tags:
  business_unit: HQ
  owner: lalitha.nagarur3@justice.gov.uk
