---
dag:
  repository: moj-analytical-services/airflow-auto-pipeline
  tag: v0.1.0
  env_vars:
    TARGET: "airflow-hello-world"

iam:
  s3_read_only:
    - alpha-corp-data-staging/*

secrets:
  - repo-key

maintainers:
  - moj-supratikc

tags:
  business_unit: Central Digital
  owner: Supratik.Chowdhury@justice.gov.uk
