---
dag:
  repository: moj-analytical-services/mlops-drone-detection
  tag: v0.1.2-rc
  compute_profile: gpu-spot-8vcpu-32gb
  env_vars:
    S3_DATA_BUCKET: "alpha-drone-detection-hackathon"
    S3_MODEL_PATH: "s3://alpha-drone-detection-hackathon/models"
    S3_EVAL_PATH: "s3://alpha-drone-detection-hackathon/evaluations"
    S3_INFERENCE_PATH: "s3://alpha-drone-detection-hackathon/inference_outputs"
    MLFLOW_TRACKING_URI: "https://mlflow.compute.development.analytical-platform.service.justice.gov.uk/"
    MLFLOW_EXPERIMENT_NAME: "mlops__drone_detection_dev"

maintainers:
  - JamesABaker
  - RossKen

iam:
  s3_read_only:
    - alpha-drone-detection-hackathon/train/*
    - alpha-drone-detection-hackathon/val/*
    - alpha-drone-detection-hackathon/test/*
  s3_read_write:
    - alpha-drone-detection-hackathon/models/*
    - alpha-drone-detection-hackathon/evaluations/*
    - alpha-drone-detection-hackathon/inference_outputs/*

notifications:
  emails:
    - james.baker2@justice.gov.uk

tags:
  business_unit: Central Digital
  owner: james.baker2@justice.gov.uk
