---
dag:
  repository: moj-analytical-services/analytical-platform-airflow-python-example
  tag: 2.1.1
  env_vars:
    MODE: "failure"
maintainers:
  - jacobwoffenden

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
