dag:
  repository: moj-analytical-services/airflow-appointment-reminders
  tag: v0.0.1.dev26
  env_vars:
    GLUE_DATABASE: "notify_raw_dev"
  tasks:
    init:
      env_vars:
        SCRIPT: "glue_database_setup.py"
    wales:
      env_vars:
        KEY_REGION: "Wales"
        SCRIPT: "extract_pipeline.py"
      dependencies: [init]
    london:
      env_vars:
        KEY_REGION: "London"
        SCRIPT: "extract_pipeline.py"
      dependencies: [init]

secrets:
  - api-key-wales
  - api-key-london

iam:
  athena: write
  glue: true
  s3_read_write:
    - alpha-asc-database/*

maintainers:
  - antonyjscott
  - sivabathina2
  - lalithanagarur

notifications:
  emails:
    - lalitha.nagarur@justice.gov.uk
    - antony.scott@justice.gov.uk
  slack_channel: data-engineering-alerts-dev

tags:
  business_unit: HQ
  owner: antony.scott@justice.gov.uk
