dag:
  repository: moj-analytical-services/airflow-appointment-reminders
  tag: v0.0.1.dev6
  env_vars:
    AWS_DEFAULT_REGION: eu-west-1

iam:
  s3_read_write:
    - alpha-asc-database/*

maintainers:
  - antonyjscott

tags:
  business_unit: HQ
  owner: antony.scott@justice.gov.uk
