dag:
  repository: moj-analytical-services/airflow-appointment-reminders
  tag: v1.1.1
  env_vars:
    GLUE_DATABASE: "appointment_reminders_raw_dev"
    S3_BUCKET: "alpha-govnotify-probation-messaging/appointment-reminders"
  tasks:
    init:
      env_vars:
        SCRIPT: "glue_database_setup.py"
    wales:
      env_vars:
        KEY_REGION: "Wales"
        SCRIPT: "extract_pipeline.py"
      dependencies: [init]
    london:
      env_vars:
        KEY_REGION: "London"
        SCRIPT: "extract_pipeline.py"
      dependencies: [init]
    east-of-england:
      env_vars:
        KEY_REGION: "East of Eng"
        SCRIPT: "extract_pipeline.py"
      dependencies: [init]
    greater-manchester:
      env_vars:
        KEY_REGION: "Greater Manch"
        SCRIPT: "extract_pipeline.py"
      dependencies: [init]
    west-midlands:
      env_vars:
        KEY_REGION: "West Midlands"
        SCRIPT: "extract_pipeline.py"
      dependencies: [init]
    kent-surrey-sussex:
      env_vars:
        KEY_REGION: "Ken Sur Sus"
        SCRIPT: "extract_pipeline.py"
      dependencies: [init]
    south-central:
      env_vars:
        KEY_REGION: "South Central"
        SCRIPT: "extract_pipeline.py"
      dependencies: [init]
    east-midlands:
      env_vars:
        KEY_REGION: "East Midlands"
        SCRIPT: "extract_pipeline.py"
      dependencies: [init]
    north-east:
      env_vars:
        KEY_REGION: "North East"
        SCRIPT: "extract_pipeline.py"
      dependencies: [init]
    north-west:
      env_vars:
        KEY_REGION: "North West"
        SCRIPT: "extract_pipeline.py"
      dependencies: [init]
    south-west:
      env_vars:
        KEY_REGION: "South West"
        SCRIPT: "extract_pipeline.py"
      dependencies: [init]
    york-humb:
      env_vars:
        KEY_REGION: "York Humb"
        SCRIPT: "extract_pipeline.py"
      dependencies: [init]

secrets:
  - api-key-wales
  - api-key-london
  - api-key-east-of-eng
  - api-key-greater-manch
  - api-key-west-midlands
  - api-key-ken-sur-sus
  - api-key-south-central
  - api-key-east-midlands
  - api-key-north-east
  - api-key-north-west
  - api-key-south-west
  - api-key-york-humb

iam:
  athena: write
  glue: true
  s3_read_write:
    - alpha-govnotify-probation-messaging/appointment-reminders/*

maintainers:
  - antonyjscott
  - lalithanagarur

notifications:
  emails:
    - lalitha.nagarur3@justice.gov.uk
    - antony.scott@justice.gov.uk
  slack_channel: de-probation-airflow-dev

tags:
  business_unit: HQ
  owner: antony.scott@justice.gov.uk
