dag:
  repository: moj-analytical-services/airflow-appointment-reminders
  tag: v0.0.1.dev12
  env_vars:
    GLUE_DATABASE: "notify_raw_dev"
  tasks:
    wales:
      env_vars:
        KEY_REGION: "Wales"
    london:
      env_vars:
        KEY_REGION: "London"

secrets:
  - api-key-wales
  - api-key-london

iam:
  s3_read_write:
    - alpha-asc-database/*

maintainers:
  - antonyjscott
  - sivabathina2
  - lalithanagarur

tags:
  business_unit: HQ
  owner: antony.scott@justice.gov.uk
