---
dag:
  repository: ministryofjustice/analytical-platform-airflow-cadet-deployer
  tag: 1.1.14
  compute_profile: general-on-demand-8vcpu-32gb
  schedule: "0 12 * * 0"
  catchup: false
  outlets:
    - "s3://mojap-derived-tables/prod/weekly/"
    - "s3://mojap-derived-tables/prod/daily/"
  env_vars:
    DEPLOY_ENV: sandpit
    DBT_PROFILE_WORKGROUP: dbt-weekly
    DBT_PROJECT: mojap_derived_tables
    WORKFLOW_NAME: deploy-weekly
    DBT_SELECT_CRITERIA: tag:daily tag:weekly
    BRANCH: main
    MODE: build
    IS_SUNDAY_RUN: true

maintainers:
  - jhpyke

secrets:
  - github-key

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/prod/*

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
