---
dag:
  repository: moj-analytical-services/airflow_mlops_training_example
  tag: 1.1.4
  compute_profile: general-spot-64vcpu-256gb

maintainers:
  - mshodge

iam:
  s3_read_only:
    - alpha-mlops-examples/insurance_example/data/*
  s3_write_only:
    - alpha-mlops-examples/insurance_example/model/*
    - alpha-analytical-platform-mlflow-development/*

secrets:
  - mlflow-tracking-username
  - mlflow-tracking-password

tags:
  business_unit: HQ
  owner: michael.hodge1@justice.gov.uk
