dag:
  repository: moj-analytical-services/ssct-manage-files
  tag: 0.0.11

iam:
  s3_read_write:
    - mojap-data-production-ssct-gov-29148-egress/*
    - mojap-data-production-shared-services-client-team-gov-29148/*

maintainers:
  - MJCT-MOJ

tags:
  business_unit: HQ
  owner: michael.terry@justice.gov.uk
