---
dag:
  repository: ministryofjustice/analytical-platform-airflow-cadet-deployer
  tag: 1.1.17
  compute_profile: general-on-demand-16vcpu-64gb
  schedule: "0 12 * * 0"
  catchup: false
  outlets:
    - "s3://mojap-derived-tables/prod/monthly/"
    - "s3://mojap-derived-tables/prod/weekly/"
    - "s3://mojap-derived-tables/prod/daily/"
  env_vars:
    DEPLOY_ENV: sandpit
    DBT_PROFILE_WORKGROUP: dbt-monthly
    DBT_PROJECT: mojap_derived_tables
    WORKFLOW_NAME: deploy-monthly
    DBT_SELECT_CRITERIA: tag:daily tag:weekly tag:monthly
    BRANCH: main
    MODE: build
    IS_SUNDAY_DEPLOY: true

maintainers:
  - jhpyke

secrets:
  - github-key

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/prod/*

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
