---
dag:
  repository: ministryofjustice/analytical-platform-airflow-cadet-deployer
  tag: 1.1.12
  compute_profile: general-on-demand-8vcpu-32gb
  schedule: "0 12 1-7 * 0"
  outlets: ["s3://mojap-derived-tables/prod/monthly/"]
  env_vars:
    DEPLOY_ENV: sandpit
    DBT_PROFILE_WORKGROUP: dbt-monthly
    DBT_PROJECT: mojap_derived_tables
    WORKFLOW_NAME: deploy-monthly
    DBT_SELECT_CRITERIA: tag:daily tag:weekly tag:monthly
    BRANCH: main
    MODE: build

maintainers:
  - jhpyke

secrets:
  - github-key

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/prod/*

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
