dag:
  repository: moj-analytical-services/airflow-create-a-pipeline
  tag: v4.0.0-alpha.1b77a60
  retries: 1
  retry_delay: 150
  max_active_runs: 5
  env_vars:
    LOG_LEVEL: "DEBUG"
    LAND: "s3://mojap-land/hmcts/xhibit"
    RAW_HIST: "s3://mojap-raw-hist/hmcts/xhibit"
    BASE_LOC: "s3://alpha-mojap-curated-xhibit/ors/v2/"
    BASE_DB_NAME: "xhibit_preprocessed"
    SERVICE: "xhibit"
    CHUNK_SIZE: "500MB"
    DAG_INTERVAL_END: "{{ data_interval_end }}"

  tasks:
    xhibit_load_[TEMPLATE]:
      env_vars:
        TABLE: "allocated_listings"
    xhibit_load_address:
      env_vars:
        TABLE: "address"
    xhibit_load_breach:
      env_vars:
        TABLE: "breach"
    xhibit_load_bw_history:
      env_vars:
        TABLE: "bw_history"
    xhibit_load_case_diary_fixture:
      env_vars:
        TABLE: "case_diary_fixture"
    xhibit_load_case_listing_entry:
      env_vars:
        TABLE: "case_listing_entry"
    xhibit_load_case_on_list:
      env_vars:
        TABLE: "case_on_list"
    xhibit_load_case_prosecutor_agency:
      env_vars:
        TABLE: "case_prosecutor_agency"
    xhibit_load_cases:
      env_vars:
        TABLE: "cases"
    xhibit_load_charge:
      env_vars:
        TABLE: "charge"
    xhibit_load_court:
      env_vars:
        TABLE: "court"
    xhibit_load_court_room_usage:
      env_vars:
        TABLE: "court_room_usage"
    xhibit_load_def_hearing_record:
      env_vars:
        TABLE: "def_hearing_record"
    xhibit_load_def_case_on_ref_sol_firm:
      env_vars:
        TABLE: "def_case_on_ref_sol_firm"
    xhibit_load_defendant:
      env_vars:
        TABLE: "defendant"
    xhibit_load_defendant_charge:
      env_vars:
        TABLE: "defendant_charge"
    xhibit_load_defendant_history:
      env_vars:
        TABLE: "defendant_history"
    xhibit_load_defendant_on_case:
      env_vars:
        TABLE: "defendant_on_case"
    xhibit_load_defendant_on_case_history:
      env_vars:
        TABLE: "defendant_on_case_history"
    xhibit_load_defendant_on_offence:
      env_vars:
        TABLE: "defendant_on_offence"
    xhibit_load_defendant_reference:
      env_vars:
        TABLE: "defendant_reference"
    xhibit_load_disposal2:
      env_vars:
        TABLE: "disposal2"
    xhibit_load_disposal_line:
      env_vars:
        TABLE: "disposal_line"
    xhibit_load_hearing:
      env_vars:
        TABLE: "hearing"
    xhibit_load_hearing_leg_rep:
      env_vars:
        TABLE: "hearing_leg_rep"
    xhibit_load_hearing_list:
      env_vars:
        TABLE: "hearing_list"
    xhibit_load_indictment_log:
      env_vars:
        TABLE: "indictment_log"
    xhibit_load_legal_aid_order:
      env_vars:
        TABLE: "legal_aid_order"
    xhibit_load_list:
      env_vars:
        TABLE: "list"
    xhibit_load_mis_event_log:
      env_vars:
        TABLE: "mis_event_log"
    xhibit_load_monetary_order_tracking:
      env_vars:
        TABLE: "monetary_order_tracking"
    xhibit_load_offence:
      env_vars:
        TABLE: "offence"
    xhibit_load_plea:
      env_vars:
        TABLE: "plea"
    xhibit_load_ref_advocate:
      env_vars:
        TABLE: "ref_advocate"
    xhibit_load_ref_app_result:
      env_vars:
        TABLE: "ref_app_result"
    xhibit_load_ref_court:
      env_vars:
        TABLE: "ref_court"
    xhibit_load_ref_cracked_effective:
      env_vars:
        TABLE: "ref_cracked_effective"
    xhibit_load_ref_disposal_line:
      env_vars:
        TABLE: "ref_disposal_line"
    xhibit_load_ref_disposal_type:
      env_vars:
        TABLE: "ref_disposal_type"
    xhibit_load_ref_event_description:
      env_vars:
        TABLE: "ref_event_description"
    xhibit_load_ref_hearing_type:
      env_vars:
        TABLE: "ref_hearing_type"
    xhibit_load_ref_judge:
      env_vars:
        TABLE: "ref_judge"
    xhibit_load_ref_legal_representative:
      env_vars:
        TABLE: "ref_legal_representative"
    xhibit_load_ref_listing_data:
      env_vars:
        TABLE: "ref_listing_data"
    xhibit_load_ref_offence:
      env_vars:
        TABLE: "ref_offence"
    xhibit_load_ref_solicitor_firm:
      env_vars:
        TABLE: "ref_solicitor_firm"
    xhibit_load_ref_system_code:
      env_vars:
        TABLE: "ref_system_code"
    xhibit_load_sched_hearing_defendant:
      env_vars:
        TABLE: "sched_hearing_defendant"
    xhibit_load_scheduled_hearing:
      env_vars:
        TABLE: "scheduled_hearing"
    xhibit_load_sh_leg_rep:
      env_vars:
        TABLE: "sh_leg_rep"
    xhibit_load_sitting:
      env_vars:
        TABLE: "sitting"
    xhibit_load_terminal:
      env_vars:
        TABLE: "terminal"
    xhibit_load_verdict:
      env_vars:
        TABLE: "verdict"

iam:
  athena: write
  s3_read_write:
    - mojap-land-dev/hmcts/common-platform/*
    - mojap-raw-hist-dev/hmcts/common-platform/*
    - alpha-mojap-common-platform/*

maintainers:
  - andy-cook

tags:
  business_unit: Central Digital
  owner: andrew.cook1@justice.gov.uk
