dag:
  repository: moj-analytical-services/prison-flows-analysis
  tag: v0.4.0.dev28

iam:
  athena: write

  s3_read_only:
    - alpha-short-term-forecast/PrisonLongLookup.csv

  s3_read_write:
    - alpha-short-term-forecast/data/*
    - alpha-short-term-forecast/files/*
    - alpha-short-term-forecast/data_folder/*

maintainers:
  - antonyjscott

tags:
  business_unit: HQ
  owner: antony.scott@justice.gov.uk
