---
dag:
  repository: moj-analytical-services/airflow-bold-rr-essex-police
  tag: v1.2.7-dev

  env_vars:
    DBT_ENV: dev
    DOMAIN: bold
    DB_NAME: bold_rr_pnc_ids
    INPUT_FILE_FORMAT: parquet
    OUTPUT_FILE_FORMAT: csv
    CONVERSION_BUCKET: alpha-bold-data-shares
    PREFIX: reducing-reoffending/essex-police-dev/pnc-id-extraction
    SFTP_BUCKET: mojap-data-production-bold-egress-development
    SFTP_BUCKET_PREFIX: essex-police
    SFTP_FILENAME: dummy_pnc_ids_to_send
    PYTHON_SCRIPT_NAME: pnc_id_extraction.py

iam:
  athena: write
  glue: true
  kms:
    - arn:aws:kms:eu-west-2:593291632749:key/mrk-6933c22d7d814cc5806fb70655a97184
    - arn:aws:kms:eu-west-1:593291632749:key/mrk-6933c22d7d814cc5806fb70655a97184
  s3_read_write:
    - alpha-bold-data-shares/reducing-reoffending/essex-police-dev/pnc-id-extraction/*
    - mojap-data-production-bold-egress-development/essex-police/*

maintainers:
  - guyvw1

tags:
  business_unit: Central Digital
  owner: guy.wheeler@justice.gov.uk
