---
dag:
  repository: moj-analytical-services/airflow-cf-misconduct
  tag: v10
  catchup: false
  schedule: "0 20 9 * *"
  tasks:
    classification-predict-inv:
      env_vars:
        EXEC_SCRIPT: "classification-predict-inv"
        EXEC_ARGS: "--env prod"
      compute_profile: gpu-spot-8vcpu-32gb

iam:
  athena: write
  s3_read_write:
    - alpha-cf-misconduct/*
    - alpha-app-fraud-and-corruption-insights/*
    - mojap-athena-query-dump/*
    - alpha-athena-query-dump/*
  s3_read_only:
    - mojap-derived-tables/prod/models/domain_name=people/database_name=counter_fraud_misconduct*
    - mojap-derived-tables/dev/models/domain_name=people/database_name=counter_fraud_misconduct*

maintainers:
  - jhenfrancis
  - sheilz81
  - maxblum31

notifications:
  emails:
    - jhenielle.francis@justice.gov.uk
    - sheila.ladva@justice.gov.uk
    - max.blum@justice.gov.uk
  slack_channel: cf-misconduct-notifications

tags:
  business_unit: HQ
  owner: jhenielle.francis@justice.gov.uk
