---
dag:
  repository: moj-analytical-services/airflow-cf-misconduct
  tag: v7.6
  catchup: false
tasks:
  db-prep-compare-labels:
    env_vars:
      EXEC_SCRIPT: "run-pipeline"
      CHECK: "db_prepared"
      SCRIPT: "compare-labels-db"

iam:
  athena: write
  s3_read_write:
    - alpha-cf-misconduct/*
    - alpha-app-fraud-and-corruption-insights/*
    - mojap-athena-query-dump/*
    - alpha-athena-query-dump/*

maintainers:
  - jhenfrancis
  - sheilz81
  - tomd-moj

notifications:
  emails:
    - jhenielle.francis@justice.gov.uk
    - sheila.ladva@justice.gov.uk
    - thomas.dykins@justice.gov.uk
  slack_channel: misconduct_nlp

tags:
  business_unit: HQ
  owner: jhenielle.francis@justice.gov.uk
