---
dag:
  repository: airflow-cjsm-email-traffic-preprocess
  tag: v5
  python_dag: true

iam:
  athena: read
  s3_read_only: 
    - alpha-cjsm-logs-data/api_test/production/processed/pass/*
  s3_write_only: # Needs to write to bucket for app data
    - alpha-app-cjsm-email-traffic/*
    - alpha-app-cjsm-networkanalysis/*

maintainers:
  - dugaldhepburnmoj

tags:
  business_unit: HQ
  owner: dugald.hepburn@justice.gov.uk