dag:
  repository: ministryofjustice/coat-copilot-usage-pipeline
  tag: v0.1.7
  catchup: false
  is_paused_upon_creation: false
  max_active_runs: 1
  retries: 1
  retry_delay: 150
  start_date: "2026-07-01"
  tasks:
    extract:
      compute_profile: "general-spot-1vcpu-4gb"
      env_vars:
        MODE: "prod"
        PROD_BUCKET: "cloud-platform-41b6a454e7cc120fe1764d3f7fe3f1e2"
        BACKFILL_RANGE: "month"

iam:
  s3_read_write:
    - cloud-platform-41b6a454e7cc120fe1764d3f7fe3f1e2/*

secrets:
  - enterprise-billing-token

maintainers:
  - mamonu
  - levgorbunov1

tags:
  business_unit: Platforms
  owner: anthony.bishop@justice.gov.uk

notifications:
  slack_channel: coat-notifications
