---
dag:
  repository: ministryofjustice/analytical-platform-airflow-cadet-deployer
  tag: 1.2.6
  compute_profile: general-on-demand-16vcpu-64gb
  schedule: "0 6 * * *"
  catchup: false
  outlets:
    - "s3://mojap-derived-tables/prod/curated-daily/"
  env_vars:
    DEPLOY_ENV: sandpit
    DBT_PROFILE_WORKGROUP: dbt-curated-daily
    DBT_PROJECT: mojap_derived_tables
    WORKFLOW_NAME: deploy-curated-daily
    DBT_SELECT_CRITERIA: tag:curated
    BRANCH: main
    MODE: build
  tasks:
    table_deploy:
      compute_profile: general-on-demand-8vcpu-32gb
    bold-rr-check:
      compute_profile: general-spot-2vcpu-8gb
      env_vars:
        IS_DATASET_CHECK: true
        UNIQUE_IDS: "model.mojap_derived_tables.bold_rr_pnc_ids__pnc_ids_to_send"
      outlets:
        - "s3://mojap-derived-tables/prod/curated-daily/bold-rr/"
      dependencies: [table_deploy]

maintainers:
  - jhpyke

secrets:
  - github-key

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/prod/*

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
