---
dag:
  repository: moj-analytical-services/airflow-file
  tag: v1.2.3
  schedule: "30 * * * *"
  is_paused_upon_creation: true
  env_vars:
    AFFILE_ALLOW_PROD: "true"
    AFFILE_ENV: "prod"
    AFFILE_SCHEMA_CONTRACT: "freeze"
    AWS_DEFAULT_REGION: "eu-west-1"
    AWS_ATHENA_QUERY_EXTRACT_REGION: "eu-west-1"
    AWS_DEFAULT_EXTRACT_REGION: "eu-west-1"
  catchup: false
  max_active_runs: 1
  retries: 2
  compute_profile: general-on-demand-2vcpu-8gb
  tasks:
    load-sop__snapshots_wf_62_sip:
      env_vars:
        AFFILE_PIPELINE_NAME: "sop__snapshots_wf62_sip"
    load-sop__all_time_hra01_non_sickness_absence:
      env_vars:
        AFFILE_PIPELINE_NAME: "sop__all_time_hra01_non_sickness_absence"
        AFFILE_SCHEMA_CONTRACT: "evolve"
    load-sop__all_time_wf59_leavers:
      env_vars:
        AFFILE_PIPELINE_NAME: "sop__all_time_wf59_leavers"
    load-sop__all_time_wf60_sickness:
      env_vars:
        AFFILE_PIPELINE_NAME: "sop__all_time_wf60_sickness"
    load-sop__all_time_wf64_starters:
      env_vars:
        AFFILE_PIPELINE_NAME: "sop__all_time_wf64_starters"
    load-sop__snapshots_hra04_non_sickness_absence:
      env_vars:
        AFFILE_PIPELINE_NAME: "sop__snapshots_hra04_non_sickness_absence"
    load-sop__snapshots_hra04_sickness_absence:
      env_vars:
        AFFILE_PIPELINE_NAME: "sop__snapshots_hra04_sickness_absence"
    load-sop__wf04_secondments:
      env_vars:
        AFFILE_PIPELINE_NAME: "sop__wf04_secondments"
    load-sop__remuneration:
      env_vars:
        AFFILE_PIPELINE_NAME: "sop__remuneration"
    load-sop__remuneration:
      env_vars:
        AFFILE_PIPELINE_NAME: "sop__all_time_wf02_tra_allowances"

iam:
  athena: write
  glue: true

  s3_read_only:
    - mojap-land/corporate/report_extractor_prod/splashbi/*

  s3_read_write:
    - mojap-processed/domain__hr/env__prod/corporate_sop/*
    - mojap-processed/domain__hr/env__prod/corporate_sop_staging/*
    - mojap-processed/domain__hr/env__prod/athena_query_dump/*
    - mojap-processed/corporate/sop/prod/*

notifications:
  slack_channel: dmet-corp-notifications

  emails:
    - Laurence.Droy@justice.gov.uk
    - William.Orr@justice.gov.uk
    - Supratik.Chowdhury@justice.gov.uk

maintainers:
  - ltd-pa
  - williamorrie
  - moj-supratikc

tags:
  business_unit: Central Digital
  owner: Laurence.Droy@justice.gov.uk
