---
dag:
  repository: moj-analytical-services/airflow-load-em-data
  tag: v0.1.73-a3066f346be51b3aa16728d801dab9a63103f7a6
  compute_profile: gpu-spot-8vcpu-32gb
  catchup: false
  depends_on_past: false
  schedule: None
  max_active_runs: 1
  env_vars:
    SUPPLIER_NAME: "serco"
    SYSTEM_NAME: "fms"
    REFRESH_TOTAL_DB: true
    AWS_DEFAULT_REGION: "eu-west-2"
    AWS_ATHENA_QUERY_EXTRACT_REGION: "eu-west-2"
    AWS_DEFAULT_EXTRACT_REGION: "eu-west-2"

notifications:
  emails:
    - EMDataEngineering@justice.gov.uk
  slack_channel: electronic-monitoring-data-hub-preprod-notifications

iam:
  external_role: arn:aws:iam::443370694497:role/airflow-prod-full-reload-fms-pp

maintainers:
  - matt-heery
  - kraihanmoj

tags:
  business_unit: HMPPS
  owner: EMDataEngineering@justice.gov.uk
