---
dag:
  repository: moj-analytical-services/laa_cwa_providers
  tag: 1.8.0
  retries: 2
  retry_delay: 150
  compute_profile: general-on-demand-8vcpu-32gb
  env_vars:
    ENVIRONMENT: "prod"
    LOG_LEVEL: "INFO"
    BUCKET_URL: >-
      s3://alpha-mojap-curated-laa/pda/raw
    CACHE_DIRECTORY: >-
      s3://alpha-mojap-curated-laa/pda/cache
    ERROR_SUMMARY_DIR: >-
      s3://alpha-mojap-curated-laa/pda/error_summaries
    QUERY_RESULT_BUCKET: >-
      s3://aws-athena-query-results-593291632749-eu-west-1
    ATHENA_WORK_GROUP: "primary"
    CACHE_ENABLED: "true"
    DISABLE_COMPRESSION: "true"
    DLTHUB_TELEMETRY: "false"
    API_REQUEST_TIMEOUT: "30"
    API_MAX_RETRIES: "2"
    DEPENDENCY_BATCH_SIZE: "100"
    API_BASE_URL: >-
      https://laa-provider-details-api-prod.apps.live.cloud-platform.service.justice.gov.uk/
    PIPELINE_DIR: "providers_staging_prod/"
    DATABASE_NAME: "laa_provider_raw"

  tasks:
    extract-provider-offices:
      env_vars:
        PIPELINE_NAME: "providers_prod_offices"
        API_ENDPOINTS: "provider_offices"
      dependencies: [extract-provider-firms]

    extract-fee-earners:
      env_vars:
        PIPELINE_NAME: "providers_prod_fee_earners"
        API_ENDPOINTS: "fee_earners"
      dependencies: [extract-provider-firms]

    extract-mediation-outreach:
      env_vars:
        PIPELINE_NAME: "providers_prod_mediation_outreach"
        API_ENDPOINTS: "mediation_outreach"
      dependencies: [extract-provider-firms]

    extract-nms-authorisation:
      env_vars:
        PIPELINE_NAME: "providers_prod_nms_authorisation"
        API_ENDPOINTS: "nms_authorisation"
      dependencies: [extract-provider-firms]

    extract-provider-users:
      env_vars:
        PIPELINE_NAME: "providers_prod_users"
        API_ENDPOINTS: "provider_users"
      dependencies: [extract-provider-firms]

iam:
  athena: write
  glue: true
  s3_read_write:
    - alpha-mojap-curated-laa/pda/*
    - aws-athena-query-results-593291632749-eu-west-1/*

secrets:
  - api-token

notifications:
  emails:
    - Ihuoma.Panton@justice.gov.uk
    - Damilola.Oyebade@justice.gov.uk
  slack_channel: laa-de-alerts

maintainers:
  - oplaa-collab
  - dami-moj

tags:
  business_unit: LAA
  owner: Ihuoma.Panton@justice.gov.uk
