---
dag:
  repository: moj-analytical-services/airflow-govuk-weekly-prison-stats-etl
  tag: v0.1.8
  schedule: "0 1 * * Tue"

iam:
  athena: write
  glue: true
  s3_read_write:
    - alpha-weekly-prison-pop-cap-publication-data/*

maintainers:
  - swalla-moj

tags:
  business_unit: HMPPS
  owner: steven.wallace1@justice.gov.uk
