---
# https://user-guidance.analytical-platform.service.justice.gov.uk/services/airflow/index.html
dag:
  repository: moj-analytical-services/airflow-cross-cjs-data
  tag: v1.0.0
  catchup: false
  compute_profile: "general-spot-8vcpu-32gb"
  depends_on_past: false
  retries: 1
  retry_delay: 150
  schedule: "0 1 13 * *"

  env_vars:
    LOG_LEVEL: "INFO"
    ENV: "prod"
    FULL_REFRESH: "false"
    S3_LAND_DELETION_FLAG: "true"
    SCRIPT_ENTRYPOINT: src/pipeline.py

  tasks:
    extraction:
      env_vars:
        SERVICE: "extract"
        SCRIPT_ENTRYPOINT: src/extraction.py

    load_postcharge:
      env_vars:
        SERVICE: "load_postcharge"
      dependencies: [extraction]

    load_postcharge_cfs:
      env_vars:
        SERVICE: "load_postcharge_cfs"
      dependencies: [extraction]

    load_precharge:
      env_vars:
        SERVICE: "load_precharge"
      dependencies: [extraction]

    load_victim_witnesses:
      env_vars:
        SERVICE: "load_victim_witnesses"
      dependencies: [extraction]

notifications:
  emails:
    - parminder.thindal@justice.gov.uk
  slack_channel: xcjs-de-alerts

iam:
  athena: write
  s3_read_write:
    - mojap-land/cps/*
    - mojap-raw-hist/crown_prosecution_service/*
    - alpha-cjs-dataset-sensitive-dip/*
    - alpha-criminal-courts-data-staging/crown_prosecution_service/*

secrets:
  - decryption-token

maintainers:
  - parminder-thindal-moj
  - ThomasHepworth
  - Andy-Cook
  - george-w-jenkins

tags:
  business_unit: HMCTS
  owner: parminder.thindal@justice.gov.uk
