---
tags:
  business_unit: HQ
  application: Analytical Platform
  is_production: false
  owner: analytical-platform@justice.gov.uk

dag:
  image:
    repository: ghcr.io/ministryofjustice/analytical-platform-airflow-python-base
    tag: 1.3.0
  compute_profile: general-spot-1vcpu-4gb
  retries: 2
  start_date: "2024-01-02"
  depends_on_past: false
  email_on_failure: false
  schedule_interval: "0 3 * * *"
  catchup: false
  max_active_tasks: 2
  description: "this is an example dag!"
  tasks:
    task_1:
      operator: airflow.providers.cncf.kubernetes.operators.kubernetes_pod.KubernetesPodOperator
      image: ghcr.io/ministryofjustice/analytical-platform-airflow-python-base:1.3.0
      config_file: "/usr/local/airflow/dags/.kube/config"
      namespace: "airflow"
    task_2:
      operator: airflow.operators.bash_operator.BashOperator
      bash_command: "echo 2"
      dependencies: [task_1]
# iam:
#   create: true
#   # external_role: arn:aws:iam::123456789012:role/external-role # This won't work while create is true
#   bedrock: true
#   kms:
#     - arn:aws:kms:eu-west-2:123456789012:key/12345678-1234-1234-1234-123456789011
#     - arn:aws:kms:eu-west-2:123456789012:key/12345678-1234-1234-1234-123456789012
#   s3:
#     deny:
#       - this-isnt-a-real-bucket-deny-1/*
#       - this-isnt-a-real-bucket-deny-2/*
#     read_only:
#       - this-isnt-a-real-bucket-read-only-1/*
#       - this-isnt-a-real-bucket-read-only-2/*
#     read_write:
#       - this-isnt-a-real-bucket-read-write-1/*
#       - this-isnt-a-real-bucket-read-write-2/*
#     write_only:
#       - this-isnt-a-real-bucket-write-only-1/*
#       - this-isnt-a-real-bucket-write-only-2/*
