---
dag:
  repository: ministryofjustice/cadet-pyspark-models-deployment
  tag: v0.0.12
  compute_profile: general-spot-64vcpu-256gb

maintainers:
  - jhpyke

secrets:
  - api-key

iam:
  s3_read_write:
    - alpha-everyone/cadet-spark-athena-test/*

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
