---
dag:
  repository: ministryofjustice/cadet-pyspark-models-deployment
  tag: v0.0.3
  compute_profile: general-spot-64vcpu-256gb

maintainers:
  - jhpyke

secrets:
  - api-key

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
