---
dag:
  repository: moj-analytical-services/airflow-matrix-scraper
  tag: v2.0.1
  python_dag: true

iam:
  athena: write
  glue: true
  s3_read_write:
    - alpha-dag-matrix/api_secrets/*
    - mojap-land/corporate/matrix/*
    - mojap-raw-hist/corporate/matrix/*
    - alpha-dag-matrix/db/prod/*

maintainers:
  - ltd-pa
  - williamorrie
  - moj-supratikc

tags:
  business_unit: Central Digital
  owner: Laurence.Droy@justice.gov.uk
