---
dag:
  repository: moj-analytical-services/airflow-file
  tag: v0.0.21-test-6
  env_vars:
    AFFILE_PIPELINE_NAME: "test_csv_encrypted"
    AFFILE_ENV: "dev"
    AFFILE_SCHEMA_CONTRACT: "freeze"
    AWS_DEFAULT_REGION: "eu-west-1"
    AWS_ATHENA_QUERY_EXTRACT_REGION: "eu-west-1"
    AWS_DEFAULT_EXTRACT_REGION: "eu-west-1"
  catchup: false
  max_active_runs: 1
  retries: 0

iam:
  athena: write
  glue: true
  s3_read_write:
    - alpha-dag-sop-data-engineering/affile-test/test-csv/*
    - mojap-processed/domain__affile/env__dev/*

secrets:
  - pgp-privatekey

notifications:
  slack_channel: dmet-corp-notifications

  emails:
    - William.Orr@justice.gov.uk

maintainers:
  - williamorrie

tags:
  business_unit: Central Digital
  owner: William.Orr@justice.gov.uk
