---
dag:
  repository: "moj-analytical-services/airflow-gifts-pipeline"
  tag: "v3.0.5"
  tasks:
    export:
      env_vars:
        PYTHON_SCRIPT_NAME: "export_extracts.py"

maintainers:
  - "pdnmoji"

iam:
  athena: write
  s3_read_only:
    - alpha-app-gifts/*
    - alpha-contracts-etl/*/jaggaer/curated/live/contracts/*

  s3_read_write:
    - alpha-app-gifts-reporting/*
    - alpha-app-gifts/jaggaer/*
