---
dag:
  repository: ministryofjustice/airflow-gifts-pipeline
  tag: v3.0.4
  catchup: false
  max_active_runs: 1
  retries: 0
  schedule_interval: "0 7 * * *"
  env_vars:
    CONFIG: |
      iam_role_name: airflow_prod_gifts
      athena:
        write: true
        dump_bucket:
          - mojap-athena-query-dump
      glue_job: false
      secrets: false
      s3:
        read_only:
          - alpha-app-gifts/*
          - alpha-contracts-etl/*/jaggaer/curated/live/contracts/*
        read_write:
          - alpha-app-gifts-reporting/*
          - alpha-app-gifts/jaggaer/*

iam:
  external_role: airflow_prod_gifts

notifications:
  slack_channel: dmet-corp-notifications
  emails:
    - Philip.neale@justice.gov.uk

maintainers:
  - pdnmoji

tags:
  business_unit: Central Digital
