dag:
  repository: moj-analytical-services/airflow-pdsai-pnd-datashare
  tag: 0.0.1
  catchup: false
  depends_on_past: false
  is_paused_upon_creation: false
  max_active_runs: 1
  retries: 3
  retry_delay: 100
  schedule: None
  start_date: "2025-10-23"
  tasks:
    task:
      compute_profile: "general-on-demand-1vcpu-4gb"

iam:
  s3_read_write:
    - alpha-app-bentham-app/*

notifications:
  emails:
    - matthew.funnell@justice.gov.uk
  slack_channel: intel-app-maintenance

maintainers:
  - mattfunnell

tags:
  business_unit: HMPPS
  owner: matthew.funnell@justice.gov.uk
