---
dag:
  repository: moj-analytical-services/airflow-report-extractor
  tag: v1.0.1
  schedule: "0 7 * * 1-5"
  env_vars:
    REPORT_APP: "splashbi"
    REPORT_RUNTIME_ENV: "prod"
    REPORT_RUN_MODE: "trigger"
  tasks:
    moj-iexp01:
      env_vars:
        REPORT_NAME: "moj-iexp01"
    laa-iexp01:
      env_vars:
        REPORT_NAME: "laa-iexp01"
    opg-iexp01:
      env_vars:
        REPORT_NAME: "opg-iexp01"
    cts-iexp01:
      env_vars:
        REPORT_NAME: "cts-iexp01"
    nms-iexp01:
      env_vars:
        REPORT_NAME: "nms-iexp01"

iam:
  s3_read_write:
    - mojap-land/corporate/report_extractor_prod/splashbi/*

secrets:
  - splashbi-credentials

notifications:
  slack_channel: dmet-corp-notifications

  emails:
    - william.orr@justice.gov.uk
    - Supratik.Chowdhury@justice.gov.uk
    - laurence.droy@justice.gov.uk

maintainers:
  - williamorrie
  - moj-supratikc
  - ltd-pa

tags:
  business_unit: Central Digital
  owner: supratik.chowdhury@justice.gov.uk
