---
dag:
  repository: moj-analytical-services/airflow-bold-rr-essex-police
  tag: v1.2.15-dev
  python_dag: true

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-land-dev/bold/essex-police/*
    - mojap-raw-hist-dev/bold/essex-police/*
    - mojap-data-production-bold-egress-development/essex-police/*

secrets:
  - gov-notify-key-dev

maintainers:
  - guyvw1

tags:
  business_unit: Central Digital
  owner: guy.wheeler@justice.gov.uk
