dag:
  repository: moj-analytical-services/prison-flows-analysis
  tag: v0.4.2.dev.4
  compute_profile: general-spot-2vcpu-8gb

iam:
  athena: write

  s3_read_only:
    - alpha-short-term-forecast/PrisonLongLookup.csv
    - mojap-derived-tables/prod/models/domain_name=courts/*
    - mojap-derived-tables/prod/models/domain_name=prison/*
    - mojap-derived-tables/prod/models/domain_name=probation/*
    - mojap-derived-tables/prod/models/domain_name=general/*

  s3_read_write:
    - alpha-short-term-forecast/data/*
    - alpha-short-term-forecast/files/*
    - alpha-short-term-forecast/data_folder/*

maintainers:
  - rolakeo-mojo
  - lhan1825
  - saimon-khan
  - fernbeedle

tags:
  business_unit: HQ
  owner: lu.han@justice.gov.uk
