dag:
  repository: moj-analytical-services/prison-flows-analysis
  tag: v0.4.4.dev4.2
  compute_profile: general-spot-2vcpu-16gb
  schedule: "0 8 * * 1"

iam:
  athena: write

  s3_read_only:
    - alpha-short-term-forecast/PrisonLongLookup.csv
    - mojap-derived-tables/prod/models/domain_name=courts/*
    - mojap-derived-tables/prod/models/domain_name=prison/*
    - mojap-derived-tables/prod/models/domain_name=probation/*
    - mojap-derived-tables/prod/models/domain_name=general/*

  s3_read_write:
    - alpha-short-term-forecast/*

maintainers:
  - rolakeo-mojo
  - lhan1825
  - Saimon-Khan
  - fernbeedle

tags:
  business_unit: HQ
  owner: lu.han@justice.gov.uk
