dag:
  repository: moj-analytical-services/airflow-vio-summary
  tag: v1.1.4
  env_vars:
    AIRFLOW_ENVIRONMENT: "DEVELOPMENT"
    IMAGE_TAG: "v1.1.4"

iam:
  athena: write

  s3_read_only:
    - alpha-safety-mi/prisons_ds/*
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_dn/*
    - mojap-derived-tables/seeds/nomis_dn/*
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_dbt/*
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_sensitive/*
    - alpha-test-iam-builer/db/*

  s3_read_write:
    - alpha-app-safety-diagnostic-tool/*

  bedrock: true

notifications:
  emails:
    - sdt-support@justice.gov.uk

maintainers:
  - miller-william

tags:
  business_unit: HMPPS
  owner: william.miller1@justice.gov.uk
