---
dag:
  repository: ministryofjustice/analytical-platform-airflow-cadet-deployer
  tag: 1.1.24
  schedule: "0 9 * * *"
  catchup: false
  env_vars:
    DEPLOY_ENV: sandpit
    DBT_PROFILE_WORKGROUP: dbt-nomis-daily
    DBT_PROJECT: mojap_derived_tables
    WORKFLOW_NAME: nomis-daily
    DBT_SELECT_CRITERIA: tag:nomis_daily
    BRANCH: main
    MODE: build
    THREAD_COUNT: 10
  tasks:
    table_deploy:
      compute_profile: general-on-demand-16vcpu-64gb
      outlets:
        - "s3://mojap-derived-tables/prod/nomis-daily/"
    bentham:
      compute_profile: general-spot-2vcpu-8gb
      env_vars:
        DATASET_TARGET: bentham.bentham_app_airflow
        IS_DATASET_CHECK: true
      outlets:
        - "s3://mojap-derived-tables/prod/bentham"

maintainers:
  - jhpyke

secrets:
  - github-key

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/prod/*

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
