---
dag:
  repository: ministryofjustice/analytical-platform-airflow-cadet-deployer
  tag: 1.2.2
  schedule: "0 10 * * *"
  catchup: false
  env_vars:
    DEPLOY_ENV: prod
    DBT_PROFILE_WORKGROUP: dbt-daily
    DBT_PROJECT: mojap_derived_tables
    WORKFLOW_NAME: deploy-corporate-hr-dm
    DBT_SELECT_CRITERIA: tag:corporate_hr_dm
    BRANCH: main
    MODE: build
  tasks:
    table_deploy:
      compute_profile: general-on-demand-8vcpu-32gb
    all_passed:
      compute_profile: general-spot-2vcpu-8gb
      env_vars:
        IS_DATASET_CHECK: true
      dependencies: [table_deploy]
      outlets:
        - "s3://mojap-derived-tables/prod/deploy-corporate-hr-dm/"

maintainers:
  - ltd-pa
  - williamorrie
  - moj-supratikc
  - jhpyke

secrets:
  - github-key

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/prod/*
    - mojap-athena-query-dump/*

notifications:
  slack_channel: dmet-corp-notifications

tags:
  business_unit: Central Digital
  owner: Laurence.Droy@justice.gov.uk
