---
dag:
  repository: moj-analytical-services/airflow-avature-scraper
  tag: v0.0.24
  schedule:
    hours: 1
  is_paused_upon_creation: false
  compute_profile: general-on-demand-2vcpu-8gb
  env_vars:
    WR_WORKGROUP: airflow-prod-workgroup-corp
    ENVIRONMENT: prod
    action: process-events

iam:
  athena: write
  s3_read_write:
    - alpha-recruitment-data-model/avature-extracts/*
    - alpha-recruitment-data-model/avature-iceberg/*
    - mojap-athena-query-dump/*

notifications:
  slack_channel: dmet-corp-notifications

  emails:
    - Laurence.Droy@justice.gov.uk
    - william.orr@justice.gov.uk
    - Supratik.Chowdhury@justice.gov.uk

maintainers:
  - ltd-pa
  - williamorrie

tags:
  business_unit: Central Digital
  owner: Laurence.Droy@justice.gov.uk
