---
dag:
  repository: ministryofjustice/analytical-platform-cadet
  tag: v0.1.1
  compute_profile: general-spot-16vcpu-64gb
  env_vars:
    DEPLOY_ENV: prod
    AWS_DEFAULT_REGION: eu-west-1
    DBT_PROFILE_WORKGROUP: dbt-prod
    DBT_PROJECT: mojap_derived_tables
    WORKFLOW_NAME: cadet-compile-airflow
    DBT_SELECT_CRITERIA: ./models/ --threads 400
    RETRY_TAGS: retry
    MODE: compile

maintainers:
  - jhpyke

secrets:
  - github-key

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/sandpit/*

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
