---
dag:
  repository: ministryofjustice/analytical-platform-airflow-cadet-deployer
  tag: 1.1.12
  compute_profile: general-on-demand-8vcpu-32gb
  env_vars:
    DEPLOY_ENV: sandpit
    DBT_PROFILE_WORKGROUP: dbt-sandpit
    DBT_PROJECT: mojap_derived_tables
    WORKFLOW_NAME: cadet-compile-airflow
    DBT_SELECT_CRITERIA: models/general/addressbase_stg
    BRANCH: main
    MODE: build

maintainers:
  - jhpyke
  - jacobwoffenden

secrets:
  - github-key

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/sandpit/*

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
