---
dag:
  repository: ministryofjustice/analytical-platform-airflow-cadet-deployer
  tag: 1.0.0
  compute_profile: general-spot-64vcpu-256gb
  env_vars:
    DEPLOY_ENV: prod
    DBT_PROFILE_WORKGROUP: dbt-docs
    DBT_PROJECT: mojap_derived_tables
    WORKFLOW_NAME: deploy-docs
    DBT_SELECT_CRITERIA: models/
    MODE: docs generate

maintainers:
  - jhpyke
  - jacobwoffenden

secrets:
  - github-key

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/sandpit/*

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
