---
dag:
  repository: ministryofjustice/analytical-platform-airflow-cadet-deployer
  tag: 1.1.0
  compute_profile: general-spot-64vcpu-256gb
  env_vars:
    DEPLOY_ENV: sandpit
    DBT_PROFILE_WORKGROUP: dbt-sandpit
    DBT_PROJECT: mojap_derived_tables
    WORKFLOW_NAME: sandpit-compile
    DBT_SELECT_CRITERIA: models/
    BRANCH: test-airflow-aware-export
    MODE: compile

maintainers:
  - jhpyke
  - jacobwoffenden

secrets:
  - github-key

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/sandpit/*

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
