---
dag:
  repository: moj-analytical-services/vast-lightgbm
  tag: 0.1.66
  max_active_runs: 50

  env_vars:
    AWS_REGION: eu-west-1
    AWS_DEFAULT_REGION: eu-west-1
    ATHENA_DB: vast_training_data
    AWS_ATHENA_S3_STAGING_DIR: s3://alpha-vast/athena-staging/
    DATASET_BASE: s3://alpha-vast

  # ---- DAG parameters: can be overridden in the Airflow UI when triggering a run ----
  params:
    # Naming / versioning
    dataset_suffix: x_structured_y_train_pos_all_bins_255_neg_multiplier_20
    model_run: first_test

    # Targets
    athena_table: "x_structured_y"
    targets: "y_h7_any y_h14_any y_h28_any"
    eval_target: y_h7_any y_h14_any y_h28_any

    # Build / sampling
    skip_build_bins: false
    neg_multiplier: 20
    train_max_pos: -1
    val_max: -1
    test_max: -1
    heldout_max: -1
    two_round: true
    bin_construct_sample_cnt: -1
    max_bin: 255

    # Tree hyperparameters
    num_boost_round: 2000
    early_stopping_rounds: 200
    learning_rate: 0.005
    num_leaves: 31
    max_depth: -1
    min_data_in_leaf: 150
    feature_fraction: 0.7
    bagging_fraction: 0.6
    bagging_freq: 1
    lambda_l1: 5.0
    lambda_l2: 10.0
    scale_pos_weight: 20.0

    # Focal Loss
    use_focal_loss: false
    focal_gamma: 2.0
    focal_alpha: 0.25

    # DART
    boosting: gbdt
    drop_rate: 0.1
    max_drop: 50
    skip_drop: 0.5

    # Evaluation
    valid_heldout: false
    ks: "0.1,0.25,0.5,1,2,5,7.5,10"
    sample_train_days: -1
    sample_val_days: -1
    sample_test_days: -1
    sample_heldout_days: -1
    eval_seed: 42
    chunksize: 50000

    # Operational evaluation
    op_splits: "val"
    op_max_coverage: 0.10
    op_min_capture: 0.10
    op_save_intervals: false
    op_burnin_days: -1
    op_min_threshold: 0.2
    op_chunksize: 50000

    # Technical
    seed: 42
    num_threads: 0
    verbosity: 1
    use_gpu: false
    gpu_device: 0

    # WANDB
    wandb_project: vast-lightgbm
    wandb_entity: alex-gower-moj-ministry-of-justice-uk
    no_wandb: false

    # Sweep parameters
    sweep_id: ""
    sweep_optimization_mode: fast
    sweep_count: 5

  compute_profile: general-spot-16vcpu-64gb

  tasks:
    build_bins:
      env_vars:
        STEP: build
        SKIP_BUILD_BINS: "{{ params.skip_build_bins | int }}"
        MAX_BIN: "{{ params.max_bin | int }}"
        NEG_MULTIPLIER: "{{ params.neg_multiplier }}"
        TRAIN_MAX_POS: "{{ params.train_max_pos }}"
        VAL_MAX: "{{ params.val_max }}"
        TEST_MAX: "{{ params.test_max }}"
        HELDOUT_MAX: "{{ params.heldout_max }}"
        TWO_ROUND: "{{ params.two_round | int }}"
        BIN_CONSTRUCT_SAMPLE_CNT: "{{ params.bin_construct_sample_cnt }}"
        TARGETS: "{{ params.targets }}"
        ATHENA_TABLE: "{{ params.athena_table }}"
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"

    train:
      dependencies:
        - build_bins
      env_vars:
        STEP: train
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        MAX_BIN: "{{ params.max_bin | int }}"
        NUM_BOOST_ROUND: "{{ params.num_boost_round }}"
        EARLY_STOPPING_ROUNDS: "{{ params.early_stopping_rounds }}"
        LEARNING_RATE: "{{ params.learning_rate }}"
        NUM_LEAVES: "{{ params.num_leaves }}"
        MAX_DEPTH: "{{ params.max_depth }}"
        MIN_DATA_IN_LEAF: "{{ params.min_data_in_leaf }}"
        FEATURE_FRACTION: "{{ params.feature_fraction }}"
        BAGGING_FRACTION: "{{ params.bagging_fraction }}"
        BAGGING_FREQ: "{{ params.bagging_freq }}"
        LAMBDA_L1: "{{ params.lambda_l1 }}"
        LAMBDA_L2: "{{ params.lambda_l2 }}"
        SCALE_POS_WEIGHT: "{{ params.scale_pos_weight }}"
        NUM_THREADS: "{{ params.num_threads }}"
        VERBOSITY: "{{ params.verbosity }}"
        SEED: "{{ params.seed }}"
        BOOSTING: "{{ params.boosting }}"
        VALID_HELDOUT: "{{ params.valid_heldout | int }}"
        DROP_RATE: "{{ params.drop_rate }}"
        MAX_DROP: "{{ params.max_drop }}"
        SKIP_DROP: "{{ params.skip_drop }}"
        USE_GPU: "{{ params.use_gpu | int }}"
        GPU_DEVICE: "{{ params.gpu_device }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"
        NO_WANDB: "{{ params.no_wandb | int }}"
        USE_FOCAL_LOSS: "{{ params.use_focal_loss | int }}"
        FOCAL_GAMMA: "{{ params.focal_gamma }}"
        FOCAL_ALPHA: "{{ params.focal_alpha }}"

    evaluate:
      dependencies:
        - train
      env_vars:
        STEP: eval
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        EVAL_TARGET: "{{ params.eval_target }}"
        KS: "{{ params.ks }}"
        SAMPLE_TRAIN_DAYS: "{{ params.sample_train_days }}"
        SAMPLE_VAL_DAYS: "{{ params.sample_val_days }}"
        SAMPLE_TEST_DAYS: "{{ params.sample_test_days }}"
        SAMPLE_HELDOUT_DAYS: "{{ params.sample_heldout_days }}"
        SEED: "{{ params.eval_seed }}"
        CHUNKSIZE: "{{ params.chunksize }}"

    evaluate_operational:
      dependencies:
        - train
      env_vars:
        STEP: op_eval
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        EVAL_TARGET: "{{ params.eval_target }}"
        OP_SPLITS: "{{ params.op_splits }}"
        OP_BURNIN_DAYS: "{{ params.op_burnin_days }}"
        OP_MIN_THRESHOLD: "{{ params.op_min_threshold }}"
        OP_CHUNKSIZE: "{{ params.op_chunksize }}"
        KS: "{{ params.ks }}"
        OP_MAX_COVERAGE: "{{ params.op_max_coverage }}"
        OP_MIN_CAPTURE: "{{ params.op_min_capture }}"
        OP_SAVE_INTERVALS: "{{ params.op_save_intervals | int }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"

    sweep_worker_01:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

    sweep_worker_02:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

    sweep_worker_03:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

    sweep_worker_04:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

    sweep_worker_05:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

    sweep_worker_06:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

    sweep_worker_07:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

    sweep_worker_08:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

    sweep_worker_09:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

    sweep_worker_10:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

    sweep_worker_11:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

    sweep_worker_12:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

    sweep_worker_13:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

    sweep_worker_14:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

    sweep_worker_15:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

    sweep_worker_16:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

    sweep_worker_17:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

    sweep_worker_18:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

    sweep_worker_19:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

    sweep_worker_20:
      dependencies:
        - build_bins
      env_vars:
        STEP: sweep_worker
        PARAM_DATASET_SUFFIX: "{{ params.dataset_suffix }}"
        PARAM_MODEL_RUN: "{{ params.model_run }}"
        TARGETS: "{{ params.targets }}"
        SWEEP_ID: "{{ params.sweep_id }}"
        SWEEP_OPTIMIZATION_MODE: "{{ params.sweep_optimization_mode }}"
        SWEEP_COUNT: "{{ params.sweep_count }}"
        WANDB_PROJECT: "{{ params.wandb_project }}"
        WANDB_ENTITY: "{{ params.wandb_entity }}"

secrets:
  - wandb-api-key

iam:
  athena: write
  s3_read_write:
    - alpha-vast/*
  s3_read_only:
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_dn/table_name=assaults/*
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_dn/table_name=involvements/*

notifications:
  emails:
    - alex.gower@justice.gov.uk
  slack_channel: vast-lightgbm-alerts

maintainers:
  - alexgower

tags:
  business_unit: HQ
  owner: alex.gower@justice.gov.uk
