---
# As per https://technical-guidance.service.justice.gov.uk/documentation/standards/documenting-infrastructure-owners.html#mandatory
tags:
  business_unit: HQ
  application: Analytical Platform
  is_production: false
  owner: analytical-platform@justice.gov.uk

iam:
  bedrock: true
  kms:
    - arn:aws:kms:eu-west-2:123456789012:key/12345678-1234-1234-1234-123456789011
    - arn:aws:kms:eu-west-2:123456789012:key/12345678-1234-1234-1234-123456789012
  s3:
    deny:
      - this-isnt-a-real-bucket-deny-1/*
      - this-isnt-a-real-bucket-deny-2/*
    read_only:
      - this-isnt-a-real-bucket-read-only-1/*
      - this-isnt-a-real-bucket-read-only-2/*
    read_write:
      - this-isnt-a-real-bucket-read-write-1/*
      - this-isnt-a-real-bucket-read-write-2/*
    write_only:
      - this-isnt-a-real-bucket-write-only-1/*
      - this-isnt-a-real-bucket-write-only-2/*
