---
dag:
  repository: moj-analytical-services/epm-filecheck
  tag: v1.0.0
  schedule: "0 7 3-10 * ? *"
iam:
  s3_read_only:
    - mojap-land/corporate/epm/*

notifications:
  slack_channel: dmet-corp-notifications

  emails:
    - Laurence.Droy@justice.gov.uk
    - Benjamin.Finucane@justice.gov.uk

maintainers:
  - ltd-pa
  - benjamin-finucane

tags:
  business_unit: Central Digital
  owner: Benjamin.Finucane@justice.gov.uk
