dag:
  repository: moj-analytical-services/p1-offloc-export
  tag: v5.2.0
  catchup: false
  depends_on_past: false
  is_paused_upon_creation: false
  max_active_runs: 1
  retries: 1
  retry_delay: 150
  schedule: None
  start_date: "2025-08-07"
  tasks:
    task:
      compute_profile: "general-on-demand-1vcpu-4gb"

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-hub-exports/p1_nomis_TEST/*

secrets:
  - user
  - pass

maintainers:
  - vonbraunbates
  - gwionap

tags:
  business_unit: Central Digital
  owner: francesca.von.braun-bates@justice.gov.uk

notifications:
  emails:
    - francesca.von.braun-bates@justice.gov.uk
  slack_channel: ct-data-engineering
