---
dag:
  repository: moj-analytical-services/airflow-load-em-data
  tag: v0.1.68
  compute_profile: gpu-spot-8vcpu-32gb
  catchup: True
  depends_on_past: True
  schedule: "0 6 * * *",  # Daily at 6am
  max_active_runs: 1
  env_vars:
    SUPPLIER_NAME: "allied"
    SYSTEM_NAME: "mdss"
    REFRESH_TOTAL_DB: true
    AWS_DEFAULT_REGION: "eu-west-2"
    AWS_ATHENA_QUERY_EXTRACT_REGION: "eu-west-2"
    AWS_DEFAULT_EXTRACT_REGION: "eu-west-2"

notifications:
  emails:
    - matt.heery@justice.gov.uk
  slack_channel: em-engineers-moj-madetech

iam:
  external_role: arn:aws:iam::443370694497:role/airflow-prod-load-mdss

maintainers:
  - matt-heery
  - pricemg

tags:
  business_unit: HMPPS
  owner: matt.heery@justice.gov.uk # for now....
