---
dag:
  repository: moj-analytical-services/airflow-govuk-bank-holidays
  tag: v0.1.6

iam:
  athena: write
  glue: true
  s3_read_write:
    - alpha-govuk-bank-holidays/*

maintainers:
  - billy-pawsey

tags:
  business_unit: HMPPS
  owner: billy.pawsey@justice.gov.uk
