---
dag:
  repository: ministryofjustice/analytical-platform-airflow-python-mlops-dag-example
  tag: 0.1.0
  python_dag: true

iam:
  bedrock: true
  s3_read_only:
    - alpha-ap-mlops-source
  s3_write_only:
    - alpha-ap-mlops-destination

secrets:
  - llm-gateway-api-key
  - llm-gateway-url

maintainers:
  - gary-h9
  - jacobwoffenden

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
