---
dag:
  repository: moj-analytical-services/analytical-platform-airflow-python-example
  tag: 2.15.0
  python_dag: true

iam:
  bedrock: true

secrets:
  - example

maintainers:
  - jacobwoffenden
  - jhpyke

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
