---
dag:
  repository: ministryofjustice/analytical-platform-mlops-dag-example
  tag: 0.1.5
  env_vars:
    S3_SOURCE_BUCKET: "alpha-ap-mlops-source"
    S3_SOURCE_KEY: "input-data.csv"
    S3_DESTINATION_BUCKET: "alpha-ap-mlops-destination"
    S3_DESTINATION_KEY: "transformed-data.csv"

iam:
  s3_read_only:
    - alpha-ap-mlops-source/*
  s3_write_only:
    - alpha-ap-mlops-destination/*

secrets:
  - llm-key
  - llm-url

maintainers:
  - Gary-H9
  - jacobwoffenden

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
