---
dag:
  repository: ministryofjustice/analytical-platform-mlops-dag-example
  tag: 0.1.1
  python_dag: true

iam:
  s3_read_only:
    - alpha-ap-mlops-source
  s3_write_only:
    - alpha-ap-mlops-destination

secrets:
  - llm-key
  - llm-url

maintainers:
  - gary-h9
  - jacobwoffenden

tags:
  business_unit: Central Digital
  owner: analytical-platform@justice.gov.uk
