dag:
  repository: airflow-cf-misconduct
  tag: v6.3
  # not sure if two rows below are needed?
  dag_id: cf_misconduct.cf_misconduct_process
  default_args: default_args
  catchup: false
  depends_on_past: false
  email_on_failure: True
  #is_paused_upon_creation: false
  #max_active_runs: 1
  #retries: 3
  #retry_delay: 100
  schedule_interval: *0 20 * * *"
  start_date: "2022-01-01"
  ds_team_email_list: ['jhenielle.francis@justice.gov.uk', 'sheila.ladva@justice.gov.uk', 'thomas.dykins@justice.gov.uk']
  owner: jhenfrancis

env:
  AWS_DEFAULT_REGION: eu-west-1
  AWS_ATHENA_QUERY_REGION: eu-west-1
  AWS_METADATA_SERVICE_TIMEOUT: 60
  AWS_METADATA_SERVICE_NUM_ATTEMPTS: 5

jobs:
  check_db_prepared:
    runs-on: ubuntu-latest
    steps:
      - name: Check DB Prepared
        run: echo "Running: pipeline-checks --check db_prepared"

  compare_labels:
    needs: check_db_prepared
    runs-on: ubuntu-latest
    steps:
      - name: Compare Labels DB
        run: echo "Running: compare-labels-db"

  copy_db:
    needs: check_db_prepared
    runs-on: ubuntu-latest
    steps:
      - name: Copy DB
        run: echo "Running: copy-db"

  check_process_sscl_reports:
    needs: copy_db
    runs-on: ubuntu-latest
    steps:
      - name: Check Process SSCL Reports
        run: echo "Running: pipeline-checks --check process_sscl_reports"

  process_sscl_reports:
    needs: check_process_sscl_reports
    runs-on: ubuntu-latest
    steps:
      - name: Process SSCL Reports
        run: echo "Running: misconduct_nlp/process_inv_cd_data/process_inv_cd_reports.py"

  check_merged_tables:
    needs: process_sscl_reports
    runs-on: ubuntu-latest
    steps:
      - name: Check Merged Tables
        run: echo "Running: pipeline-checks --check merged_tables"

  merged_tables:
    needs: check_merged_tables
    runs-on: ubuntu-latest
    steps:
      - name: Create Merged Tables
        run: echo "Running: misconduct_nlp/process_inv_cd_data/create_merged_tables.py"

  check_tags:
    needs: merged_tables
    runs-on: ubuntu-latest
    steps:
      - name: Check Tags
        run: echo "Running: pipeline-checks --check tags"

  tags:
    needs: check_tags
    runs-on: ubuntu-latest
    steps:
      - name: Run Tagging Process
        run: echo "Running: tagging-process"

  check_tables_w_tags:
    needs: tags
    runs-on: ubuntu-latest
    steps:
      - name: Check Tables with Tags
        run: echo "Running: pipeline-checks --check tables_w_tags"

  tables_w_tags:
    needs: check_tables_w_tags
    runs-on: ubuntu-latest
    steps:
      - name: Create Tagged Employee DB
        run: echo "Running: misc_nlp/process_inv_cd_data/create_employee_tagged_db.py"

  check_generate_reports:
    needs: tables_w_tags
    runs-on: ubuntu-latest
    steps:
      - name: Check Generate Reports
        run: echo "Running: pipeline-checks --check generate_reports"

  generate_reports:
    needs: check_generate_reports
    runs-on: ubuntu-latest
    steps:
      - name: Generate All Reports
        run: echo "Running: misconduct_nlp/etl_subtasks/generate_all_reports.py"

  check_model_metrics:
    needs: tables_w_tags
    runs-on: ubuntu-latest
    steps:
      - name: Check Model Metrics
        run: echo "Running: pipeline-checks --check model_metrics"

  model_metrics_evidently:
    needs: check_model_metrics
    runs-on: ubuntu-latest
    steps:
      - name: Run Evidently AI
        run: echo "Running: misconduct-evidently-ai"

  model_metrics:
    needs: model_metrics_evidently
    runs-on: ubuntu-latest
    steps:
      - name: Run Model Metrics
        run: echo "Running: model-monitoring-metrics"


iam:
  # athena: write
  # glue: true
  # s3_read_write:
  #   - alpha-mojap-ccde/dev/pcol_raw_data/*

secrets:
  # - pds

# notifications:
#   emails:
#     - Jhenielle.Francis@justice.gov.uk

maintainers:
  - jhenfrancis
  - sheilz81
  - tomd-moj

tags:
  business_unit: HQ
  owner: Jhenielle.Francis@justice.gov.uk
