---
dag:
  repository: moj-analytical-services/airflow-avature-scraper
  tag: v0.0.22-test-01
  schedule: "0-59 * * * *"
  is_paused_upon_creation: true
  catchup: false
  max_active_runs: 1
  retries: 0
  compute_profile: general-on-demand-1vcpu-4gb
  env_vars:
    action: scrape-store-plain-json-latest
    WR_WORKGROUP: airflow-prod-workgroup-corp

iam:
  athena: write
  s3_read_write:
    - alpha-corp-secrets/avature/*
    - alpha-recruitment-data-model/avature-extracts/*
    - alpha-recruitment-data-model/avature-iceberg/*

secrets:
  - service-account-token

notifications:
  slack_channel: dmet-corp-avature-notifications

  emails:
    - Laurence.Droy@justice.gov.uk
    - william.orr@justice.gov.uk
    - Supratik.Chowdhury@justice.gov.uk

maintainers:
  - ltd-pa
  - williamorrie

tags:
  business_unit: Central Digital
  owner: Laurence.Droy@justice.gov.uk
