---
dag:
  repository: moj-analytical-services/mbpr-airflow-pipelines
  tag: v1.0.9
  env_vars:
    MODE: "opg-usat"

maintainers:
  - scott-lowther

iam:
  s3_read_write:
    - alpha-mission-brilliant-performance-reporting/*

tags:
  business_unit: Central Digital
  owner: scott.lowther@justice.gov.uk
