---
dag:
  repository: moj-analytical-services/mbpr-airflow-pipelines
  tag: v1.1.2
  env_vars:
    MODE: "opg-usat"

maintainers:
  - mikeAdamsMOJ
  - calumabarnett

iam:
  s3_read_write:
    - alpha-mission-brilliant-performance-reporting/*

tags:
  business_unit: Central Digital
  owner: Calum.Barnett@justice.gov.uk
