dag:
  repository: moj-analytical-services/airflow-sdp-extraction-legacy
  tag: v1.0.0-alpha.cc4b2f3
  retries: 1
  retry_delay: 150
  hmcts_sdp_networking: True
  max_active_runs: 3
  env_vars:
    TASK: "extract"
    LOG_LEVEL: "DEBUG"
    ENDPOINT: "BAIS_BAU_PROD"
    COPY_MODE: "all"
    LAND_BUCKET: "s3://mojap-land-dev"
    LAND_FOLDER: "hmcts/cad"
    EXCLUDED_FILES_REGEXPR: "(?i)^.*test.*$"

  tasks:
    hocas_extract:
      env_vars:
        TABLE_NAME: "baiscontainer"

iam:
  athena: write
  s3_read_write:
    - mojap-land-dev/hmcts/cad/*

secrets:
  - sdp-pass

maintainers:
  - Andy-Cook
  - jovita-brundziene

tags:
  business_unit: Central Digital
  owner: andrew.cook1@justice.gov.uk
