dag:
  repository: moj-analytical-services/airflow-assault-reasons-locations
  tag: v0.5.0
  env_vars:
    AIRFLOW_ENVIRONMENT: "PRODUCTION" #to be changed to dev once we have a prod DAG running

iam:
  athena: write

  s3_read_only:
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_dn/*
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_dbt/*
    - mojap-derived-tables/seeds/nomis_dn/*
    - alpha-anvil/*
    - alpha-anvil-lookups/*

  s3_read_write:
    - alpha-safety-mi/prisons_ds/assaults_proc_locations/*

notifications:
  emails:
    - sdt-support@justice.gov.uk

maintainers:
  - miller-william

tags:
  business_unit: HMPPS
  owner: william.miller1@justice.gov.uk
