---
dag:
  repository: moj-analytical-services/airflow-cloudwatch-logs
  tag: v1.0.0
  compute_profile: "general-on-demand-2vcpu-8gb"
  schedule: "0 6 * * *"
  env_vars:
    AWS_DEFAULT_REGION: "eu-west-1"
    AWS_REGION: "eu-west-1"
    ENVIRONMENT: "prod"
  tasks:
    cloudwatch-extract:
      env_vars:
        SOURCE: "cloudwatch_athena_logs"
        TASK: "cloudwatch"
        PYTHON_SCRIPT_NAME: "main.py"
    athena-extract:
      env_vars:
        SOURCE: "athena_queries"
        TASK: "athena"
        PYTHON_SCRIPT_NAME: "main.py"

iam:
  athena: write
  glue: true
  cloudwatch_logs_read_only:
    - arn:aws:logs:eu-west-2:593291632749:log-group:cloudtrail-athena-events:*
  s3_read_write:
    - mojap-land/athena_query_executions/prod/cloudwatch_athena_logs/*
    - mojap-land/athena_query_executions/prod/athena_queries/*


notifications:
  slack_channel: dmet-corp-notifications

  emails:
    - Supratik.Chowdhury@justice.gov.uk
    - sai.dasari3@justice.gov.uk

maintainers:
  - moj-supratikc
  - sdasarimoj

tags:
  business_unit: Central Digital
  owner: Supratik.Chowdhury@justice.gov.uk
