dag:
  repository: moj-analytical-services/airflow-sdp-extraction
  tag: v4.3.1
  start_date: "2026-10-01"
  schedule: 30 2 * * *
  retries: 0
  hmcts_sdp_networking: True
  max_active_runs: 1
  env_vars:
    LOG_LEVEL: "INFO"
    ENDPOINT: "MI_PERSISTENT_PROD"
    SDP_TABLE_PREFIX: "v3-et-employment-"
    FILENAME_COL_NAME: "meta__source_file"
    EXCLUDED_FILES_REGEXPR: "_metadata.json$"
    DATABASE_NAME: "employment_tribunals_v1"
    LAND_BUCKET: "mojap-land"
    LAND_PATH: "hmcts/employment-tribunals/"
  tasks:
    et_extract_et_englandwales:
      env_vars:
        AZURE_TABLE: "et-englandwales"
      compute_profile: general-on-demand-16vcpu-64gb
    et_extract_et_englandwales_listings:
      env_vars:
        AZURE_TABLE: "et-englandwales-listings"
    et_extract_et_englandwales_multiple:
      env_vars:
        AZURE_TABLE: "et-englandwales-multiple"

iam:
  athena: write
  s3_read_write:
    - mojap-land/hmcts/employment-tribunals/*
    - mojap-raw-hist/hmcts/employment-tribunals/*

secrets:
  - sdp-pass

notifications:
  slack_channel: dmet-hmcts-notifications

maintainers:
  - Andy-Cook
  - DanJ-MOJ
  - AntonyJScott

tags:
  business_unit: Central Digital
  owner: cft_data_engineering@justice.gov.uk