---
dag:
  repository: moj-analytical-services/airflow-load-em-data
  tag: v0.2.9-98e46d1
  compute_profile: gpu-spot-8vcpu-32gb
  catchup: false
  depends_on_past: false
  schedule: None
  max_active_runs: 1
  env_vars:
    SUPPLIER_NAME: "g4s"
    SYSTEM_NAME: "gps"
    TABLE_NAME: subject_positions
    AWS_DEFAULT_REGION: "eu-west-2"
    AWS_ATHENA_QUERY_EXTRACT_REGION: "eu-west-2"
    AWS_DEFAULT_EXTRACT_REGION: "eu-west-2"

notifications:
  emails:
    - Matt.Heery@justice.gov.uk
    - Khristiania.Raihan@justice.gov.uk
  slack_channel: em-engineers-moj-madetech

iam:
  external_role: arn:aws:iam::976799291502:role/airflow-prod-full-reload-gps

maintainers:
  - matt-heery
  - kraihanmoj

tags:
  business_unit: HMPPS
  owner: matt.heery@justice.gov.uk # for now....
