dag:
  repository: moj-analytical-services/airflow-pdsai-nca-datashare
  tag: v1.2.1
  catchup: false
  depends_on_past: false
  is_paused_upon_creation: false
  max_active_runs: 1
  retries: 0
  retry_delay: 100
  schedule: "0 0 1 2-8/6 *"
  start_date: "2025-07-01"
  tasks:
    task:
      compute_profile: "general-on-demand-1vcpu-4gb"

iam:
  s3_read_write:
    - alpha-app-bentham-app/data/databases/intel/*
    - mojap-hub-exports/nca_siezed_media/*

notifications:
  emails:
    - francesca.von.braun-bates@justice.gov.uk
    - matthew.funnell@justice.gov.uk
  slack_channel: ct-data-engineering

maintainers:
  - vonbraunbates
  - mattfunnell

tags:
  business_unit: HMPPS
  owner: matthew.funnell@justice.gov.uk
