dag:
  repository: ministryofjustice/analytical-platform-airflow-cadet-deployer
  tag: 1.3.8
  params:
    output_name: example
  env_vars:
    DEPLOY_ENV: dev
    DBT_PROFILE_WORKGROUP: dbt-dev
    DBT_PROJECT: mojap_derived_tables
    WORKFLOW_NAME: cadet-data-first-dev
    DBT_SELECT_CRITERIA: "tag:data_first_{{ params.output_name }}"
    BRANCH: main
    MODE: build
    THREAD_COUNT: 10

maintainers:
  - tmpks

tags:
  business_unit: HQ
  owner: tapan.perkins@justice.gov.uk

notifications:
  emails:
    - tapan.perkins@justice.gov.uk

secrets:
  - github-key
  - data-first-salt

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/dev/*
