---
dag:
  repository: ministryofjustice/analytical-platform-airflow-cadet-deployer
  tag: 1.3.3
  catchup: false
  env_vars:
    DEPLOY_ENV: dev
    DBT_PROFILE_WORKGROUP: dbt-oasys-question
    DBT_PROJECT: mojap_derived_tables
    WORKFLOW_NAME: deploy-oasys-question
    DBT_SELECT_CRITERIA: tag:oasys_question_only
    BRANCH: update-oasys-question-naming
    MODE: build

maintainers:
  - jhpyke
  - lalithanagarur

secrets:
  - github-key

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/dev/*

notifications:
  emails:
    - lalitha.nagarur3@justice.gov.uk
  slack_channel: de-probation-airflow-dev

tags:
  business_unit: HQ
  owner: lalitha.nagarur3@justice.gov.uk
