dag:
  repository: moj-analytical-services/airflow-shs-qual
  tag: v1.5.9
  schedule:
    datasets:
      - "s3://alpha-safety-mi/prisons_ds/dev_selfharm_proc/"
  env_vars:
    AIRFLOW_ENVIRONMENT: "DEVELOPMENT" #to be changed to dev once we have a prod DAG running
  inlets:
    - "s3://alpha-safety-mi/prisons_ds/dev_selfharm_proc/"
  outlets:
    - "s3://alpha-app-safety-diagnostic-tool/development/txt_sh_pop.feather"

iam:
  athena: write

  s3_read_only:
    - alpha-nomis/nomis_dn/*
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_dbt/*
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_sensitive/*
    - alpha-safety-mi/prisons_ds/*
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_dn/*
    - mojap-derived-tables/seeds/nomis_dn/*

  s3_read_write:
    - alpha-app-safety-diagnostic-tool/*

notifications:
  emails:
    - sdt-support@justice.gov.uk

maintainers:
  - miller-william

tags:
  business_unit: HMPPS
  owner: william.miller1@justice.gov.uk
