---
dag:
  repository: moj-analytical-services/laa-search-index-airflow-source
  tag: v0.1.13-alpha-efb72fb

iam:
  s3_read_write:
    - laa-search-audit/*
    - laa-splink-source-file-input/*
    - laa-splink-source-file-output/*
    - laa-splink-source-zip/*

  s3_read_only:
    - laa-splink-source-s3/*

  kms:
    - arn:aws:kms:eu-west-2:593291632749:key/c0f20b2d-7b3e-4a60-9c04-2fb3befe6a3f

maintainers:
  - nina-knowles-justice
  - dami-moj

secrets:
  - source-request-bucket
  - source-request-key
  - source-output-bucket
  - source-file-bucket
  - audit-bucket
  - splink-parquet

notifications:
  slack_channel: laa-search-index-alerts

tags:
  business_unit: LAA
  owner: LAA-Data-Engineering@justice.gov.uk
