---
dag:
  repository: moj-analytical-services/airflow-bold-case-info-dashboard
  tag: v1.0.69-dev

  env_vars:
    AIRFLOW_TASK: lao_audit
    R_CONFIG_ACTIVE: dev

iam:
  athena: write
  glue: true
  s3_read_write:
    - mojap-derived-tables/prod/models/domain_name=probation/database_name=delius/*
    - mojap-derived-tables/seeds/bold_rr_seeds_dev_dbt/dummy_probation_notification/*
    - alpha-bold-rr-case-info-dashboard-usage/audit/dev/*

secrets:
  - cid-notify-api-key-dev
  - audit-key-password-dev

maintainers:
  - guyvw1

tags:
  business_unit: Central Digital
  owner: guy.wheeler@justice.gov.uk
