dag:
  repository: moj-analytical-services/airflow-sdt
  tag: v4.3.5
  compute_profile: "general-spot-2vcpu-8gb"
  env_vars:
    AIRFLOW_ENVIRONMENT: "DEVELOPMENT"
  inlets:
    - ["s3://alpha-viper/scores_2_dev",
      "s3://alpha-safety-mi/test/assaults_proc/assaults_proc.csv",
      "s3://alpha-app-safety-diagnostic-tool/development/txt_sh_pop.feather",
      "s3://alpha-app-safety-diagnostic-tool/vio-summary/summary_dev.csv]
    schedule:
      datasets:
        - ["s3://alpha-viper/scores_2_dev",
          "s3://alpha-safety-mi/test/assaults_proc/assaults_proc.csv",
          "s3://alpha-app-safety-diagnostic-tool/development/txt_sh_pop.feather",
          "s3://alpha-app-safety-diagnostic-tool/vio-summary/summary_dev.csv]

iam:
  athena: write

  s3_read_only:
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_dbt/*
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_sensitive/*
    - alpha-safety-mi/prisons_ds/*
    - alpha-viper/*
    - alpha-test-iam-builer/db/*
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=nomis_dn/*
    - mojap-derived-tables/prod/models/domain_name=prison/database_name=prison_derived/*
    - mojap-derived-tables/seeds/nomis_dn/*
    - mojap-derived-tables/seeds/nomis_dn/*
    - alpha-nomis/nomis_dn/*

  s3_read_write:
    - alpha-anvil-lookups/*
    - alpha-app-safety-diagnostic-tool/*

notifications:
  emails:
    - sdt-support@justice.gov.uk

maintainers:
  - miller-william
  - lauratraceymoj

tags:
  business_unit: HMPPS
  owner: william.miller1@justice.gov.uk
