dag:
  repository: airflow-cf-misconduct
  tag: v4.9
  # not sure if two rows below are needed?
  dag_id: cf_misconduct.cf_misconduct_predictions
  default_args: default_args
  #catchup: false
  depends_on_past: false
  email_on_failure: True
  ds_team_email_list: = ['jhenielle.francis@justice.gov.uk', 'sheila.ladva@justice.gov.uk', 'thomas.dykins@justice.gov.uk']
  email: ds_team_email_list
  #is_paused_upon_creation: false
  #max_active_runs: 1
  #retries: 3
  #retry_delay: 100
  schedule: None
  start_date: "2022-01-01"

  tasks:
    evidently-reports:
      env_vars:
        CONTAINER_NAME: "evidently-reports"
        PYTHON_SCRIPT_NAME: "testevidently.py",
        AWS_METADATA_SERVICE_TIMEOUT: "60"
        AWS_METADATA_SERVICE_NUM_ATTEMPTS": "5"
        AWS_DEFAULT_REGION": "eu-west-1"
        
tasks

iam:
  # athena: write
  # glue: true
  # s3_read_write:
  #   - alpha-mojap-ccde/dev/pcol_raw_data/*

secrets:
  # - pds

# notifications:
#   emails:
#     - Jhenielle.Francis@justice.gov.uk

maintainers:
  - jhenfrancis
  - sheilz81
  - tomd-moj

tags:
  business_unit: HQ
  owner: Jhenielle.Francis@justice.gov.uk
