---
dag:
  repository: moj-analytical-services/airflow-load-em-data
  tag: v0.2.112
  compute_profile: general-on-demand-4vcpu-16gb
  catchup: false
  depends_on_past: false
  max_active_runs: 1
  env_vars:
    SUPPLIER_NAME: "g4s"
    SYSTEM_NAME: "atrium"
    SCHEMA_NAME: "dbo"
    AWS_METADATA_SERVICE_TIMEOUT: 60
    AWS_METADATA_SERVICE_NUM_ATTEMPTS: 5
    AWS_DEFAULT_REGION: "eu-west-2"
    AWS_ATHENA_QUERY_EXTRACT_REGION: "eu-west-2"
    AWS_DEFAULT_EXTRACT_REGION: "eu-west-2"

  tasks:
    load_atrium_document:
      env_vars:
        TABLE_NAME: "Document"

    load_atrium_document_detail:
      env_vars:
        TABLE_NAME: "DocumentDetail"

    load_atrium_document_type:
      env_vars:
        TABLE_NAME: "DocumentType"

    load_atrium_server:
      env_vars:
        TABLE_NAME: "Server"

    load_atrium_server_mapping:
      env_vars:
        TABLE_NAME: "ServerMapping"

    load_atrium_user:
      env_vars:
        TABLE_NAME: "User"

notifications:
  emails:
    - EMDataEngineering@justice.gov.uk
  slack_channel: em-engineers-moj-madetech

iam:
  external_role: arn:aws:iam::976799291502:role/airflow-prod-load-atrium

maintainers:
  - matt-heery
  - kraihanmoj
  - luke-a-williams

tags:
  business_unit: HMPPS
  owner: EMDataEngineering@justice.gov.uk
