---
name: 🔬 Lint

on:
  pull_request:

permissions: {}

jobs:
  actionlint:
    name: 🔎 actionlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1.43.0
        with:
          reporter: github-pr-check