---
name: 🧪 Scripts Unit Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "scripts/**"
      - "airflow/**"
      - "tests/**"
      - ".github/workflows/scripts-tests.yml"

permissions: {}

jobs:
  test-example-workflows:
    name: 🧪 Test Example Workflows
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set Up UV
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          activate-environment: true
          version: "latest"

      - name: Install Requirements
        run: |
          uv pip install --requirements requirements.txt

      - name: Run Workflow Tests
        run: make test WORKERS=4
