---
name: 🧪 Scripts Unit Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "scripts/**"
      - "airflow/**"
      - "tests/**"
      - ".github/workflows/scripts-tests.yml"

permissions: {}

jobs:
  test-example-workflows:
    name: 🧪 Test Example Workflows
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set Up UV
        uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
        with:
          activate-environment: true
          version: "latest"

      - name: Install Requirements
        run: |
          uv pip install --requirements requirements.txt

      - name: Run Workflow Tests
        run: make test WORKERS=4
